# ABL Bio Competitors with US Jurisdiction
What are companies in the ADC Onology market doing in terms of patent strategy?
- Are they developing more composition patents? CMC or clinical filings?

So I moved onto the `US-enforced-patents.jsonl` file, which focused on the US patent records
- This has also already been narrowed down to ADC Oncology related by specifying the CDCs in The Lens search
- jsonl file was used to get claims column
- This is because when bulk exporting as a csv from The Lens, only text you will get back is Title and Abstract columns
- A lot of patents will try to hide from competitors, making titles and abstracts vague
- Therefore, the jsonl file, which contains the claims, was used for subsequent analysis

### **Focus on Claims, the Legally Enforceable Scope**  
This project will focus on the independent claims section, which defines the legally enforceable scope of protection
- In Title and Abstract, companies may try to hide from other competitors and use more general terminallogy
- In Specification, you'll see occurences with broad and wide mention like:  
   - _"[0339] The cancer cell target antigen may be, for example, 5T4, ABL, ABCF1, ACVR1, ACVR1B, ACVR2, ACVR2B, ACVRL1, ADORA2A, AFP, Aggrecan, AGR2, AICDA, AIF1, AIGI, AKAP1, AKAP2, ALCAM, ALK, AMH, AMHR2, ANGPT1, ANGPT2, ANGPTL3, ANGPTL4, ANPEP, APC, APOCl, AR, aromatase, ASPH, ATX, AX1, AXL, AZGP1 (zinc-a-glycoprotein), B4GALNT1, B7, B7.1, B7.2, B7-H1, B7-H3, B7-H4, B7-H6, BAD, BAFF, BAG1, BAIl, BCR, BCL2, BCL6, BCMA, BDNF, BLNK, BLR1 (MDR15), BIyS, BMP1, BMP2, BMP3B (GDFIO), BMP4, BMP6, BMP8, BMP10, BMPR1A, BMPR1B, BMPR2, BPAG1 (Plectin), BRCA1, C19orflO (IL27w), C3, C4A, C5, C5R1, CA ...."_  
    - This will generate substantial noise


### **AI-Assisted Claim Classification**:
I will be using AI-assisted claim classification on these 2331 patents to classify into patent types
- This will provide a larger overview of types of patents being pursued by various competitors

**Note**:
- Patents do not contain an official “type” category (and can be mixed/hybrid)
- Instead, this classification will be derived from analysis of the broadest independent claim to determine the dominant functional category of the filing

<br>

---

In [187]:
import pandas as pd

df = pd.read_json("../data/raw/US-enforced-patents.jsonl", lines=True)

print(len(df))
print(df.columns)
df.head()

2331
Index(['lens_id', 'jurisdiction', 'doc_number', 'kind', 'date_published',
       'doc_key', 'docdb_id', 'lang', 'biblio', 'families', 'sequence_listing',
       'legal_status', 'abstract', 'claims', 'description',
       'publication_type'],
      dtype='object')

,lens_id,jurisdiction,doc_number,kind,date_published,doc_key,docdb_id,lang,biblio,families,sequence_listing,legal_status,abstract,claims,description,publication_type
0,001-164-692-658-169,US,9107960,B2,2015-08-18,US_9107960_B2_20150818,443471947,en,{'publication_reference': {'jurisdiction': 'US...,{'simple_family': {'members': [{'document_id':...,"{'sequence_types': ['P'], 'length_buckets': ['...","{'granted': True, 'grant_date': '2015-08-18', ...",[{'text': 'The present invention concerns impr...,[{'claims': [{'claim_text': ['1. A method to p...,{'text': 'RELATED APPLICATIONS This applicatio...,GRANTED_PATENT
1,039-300-232-515-637,US,9334318,B1,2016-05-10,US_9334318_B1_20160510,452042120,en,{'publication_reference': {'jurisdiction': 'US...,{'simple_family': {'members': [{'document_id':...,"{'sequence_types': ['DNA', 'N', 'P'], 'length_...","{'granted': True, 'grant_date': '2016-05-10', ...","[{'text': 'Novel modulators, including antibod...",[{'claims': [{'claim_text': ['1. A multivalent...,{'text': 'CROSS REFERENCED APPLICATIONS This a...,GRANTED_PATENT
2,094-825-731-979-424,US,12318455,B2,2025-06-03,US_12318455_B2_20250603,631938788,en,{'publication_reference': {'jurisdiction': 'US...,{'simple_family': {'members': [{'document_id':...,"{'sequence_types': ['P'], 'length_buckets': ['...","{'granted': True, 'grant_date': '2025-06-03', ...",[{'text': 'An anti-human epidermal growth fact...,[{'claims': [{'claim_text': ['1. An antibody-d...,{'text': 'CROSS-REFERENCE TO RELATED APPLICATI...,GRANTED_PATENT
3,165-451-121-516-190,US,20160129013,A1,2016-05-12,US_20160129013_A1_20160512,452234872,en,{'publication_reference': {'jurisdiction': 'US...,{'simple_family': {'members': [{'document_id':...,NaN,"{'granted': True, 'grant_date': '2017-03-14', ...",[{'text': 'Provided are Conjugate comprising P...,[{'claims': [{'claim_text': ['1 . A method of ...,{'text': 'The present invention relates to tar...,PATENT_APPLICATION
4,064-424-066-709-583,US,11944689,B2,2024-04-02,US_11944689_B2_20240402,609044858,en,{'publication_reference': {'jurisdiction': 'US...,{'simple_family': {'members': [{'document_id':...,NaN,"{'granted': True, 'grant_date': '2024-04-02', ...",[{'text': 'Compounds and compositions are disc...,[{'claims': [{'claim_text': ['1. A Ligand Drug...,{'text': 'CROSS-REFERENCE TO RELATED APPLICATI...,GRANTED_PATENT

In [188]:
df["claims"].apply(type).value_counts()
#output shows 9 are float, so NaN

claims
<class 'list'>     2322
<class 'float'>       9
Name: count, dtype: int64

In [189]:
#Looking at claims value for first row
df["claims"].iloc[0]

[{'claims': [{'claim_text': ['1. A method to produce a compound, CL2A-SN-38, of the structure,',
     'comprising performing a reaction scheme as shown:',
     'further comprising reacting SN-38 with tert-butyldimethylsilsl chloride (TBDMS-Cl) to produce 10-O-TBDMS-SN-38 (intermediate 4), wherein the reaction is carried out in dichloromethane solvent.']},
   {'claim_text': ['2. The method of claim 1 , further comprising reacting 10-O-TBDMS-SN-38 (intermediate 4) with triphosgene and DMAP to make 10-O-TBDMS-SN-38-20-O-chloroformate (reactive intermediate 5), wherein the reaction is performed by adding triphosgene to a dichloromethane reaction mixture that contains intermediate 4, and the triphosgene is added in portions, to reduce exothermic reaction during large scale manufacture and maintain high reaction yield.']},
   {'claim_text': ['3. The method of claim 1 , further comprising precipitating Lys(MMT)-PABOH (intermediate 2) with heptane.']},
   {'claim_text': ['4. The method of claim 3 , further comprising assaying residual diethylamine in the precipitated intermediate 2 and purifying the precipitate by chromatography if the presence of diethylamine was detected.']},
   {'claim_text': ['5. The method of claim 1 , further comprising reacting azido-PEG-Lys(MMT)-PABO-CO-20-O-SN-38 (intermediate 7) with MCC-Yne (intermediate 8) by a copper catalyzed cycloaddition reaction to make MCC-PEG-Lys(MMT)-PABO-CO-20-O-SN-38 (intermediate 9), wherein the reaction is carried out for 14 h to improve product yield.']},
   {'claim_text': ['6. The method of claim 5 , wherein intermediate 9 is first purified by silica gel chromatography, followed by extraction with EDTA to remove copper.']},
   {'claim_text': ['7. The method of claim 1 , further comprising reacting a maleimide moiety of CL2A-SN38 with a protein or peptide to make an SN38-conjugated protein or peptide.']},
   {'claim_text': ['8. The method of claim 7 , wherein the maleimide moiety reacts with a reduced sulfhydryl on the protein or peptide.']},
   {'claim_text': ['9. The method of claim 7 , wherein the protein or peptide is an antibody or an antigen-binding antibody fragment and the SN-38 conjugated antibody or antibody fragment is an immunoconjugate.']},
   {'claim_text': ['10. The method of claim 9 , further comprising purifying the immunoconjugate by tangential flow filtration (TFF).']},
   {'claim_text': ['11. The method of claim 9 , wherein the TFF is performed with a 50,000 Dalton molecular weight cut-off membrane using 25- to 30-diafiltration volumes of buffer.']},
   {'claim_text': ["12. The method of claim 11 , further comprising formulating the immunoconjugate in Good's biological buffer at a pH of 6.0 to 7.0, and lyophilizing the immunoconjugate for storage."]},
   {'claim_text': ["13. The method of claim 12 , wherein the Good's biological buffer is selected from the group consisting of 2-(N-morpholino)ethanesulfonic acid (MES), 3-(N-morpholino)propanesulfonic acid (MOPS), 4-(2-hydroxyethyl)piperazine-1-ethanesulfonic acid (HEPES), and 1,4-piperazinediethanesulfonic acid (PIPES), in the pH range of 6-7, preferably in the pH range of 6.5 to 7, and at a buffer concentration of 10-100 mM, preferably 25 mM."]},
   {'claim_text': ['14. The method of claim 13 , wherein the buffer is 25 mM MES buffer, pH 6.5.']},
   {'claim_text': ['15. The method of claim 9 , wherein the antibody is a bispecific antibody or a monoclonal antibody.']},
   {'claim_text': ['16. The method of claim 9 , wherein the antibody fragment is selected from the group consisting of F(ab′) 2 , F(ab) 2 , Fab′, Fab, Fv, scFv, single domain antibody and half-molecule of IgG4 antibody.']},
   {'claim_text': ['17. The method of claim 9 , wherein the antibody or antibody fragment is attached to between 1 and 12 copies of CL2A-SN38.']},
   {'claim_text': ['18. The method of claim 9 , wherein the antibody or antibody fragment is attached to 6 copies of CL2A-SN38.']},
   {'claim_text': ['19. The method of claim 9 , wherein the antibody or antibody fragment is attached to between 1 and 5 copies of CL2A-SN38.']},
   {'claim_text': ['20. The method of claim 9 , wherein the antibody is an anti-cancer antibody, an anti-infectious disease antibody, or an anti-autoimmune disease antibody.']},
   {'claim_text': ['21. The method of claim 9 , wherein the antibody is selected from the group consisting of LL1 (anti-CD74), LL2 (anti-CD22), RFB4 (anti-CD22), RS7 (anti-EGP-1), PAM4 (anti-MUC5AC), KC4 (anti-mucin), A19 (anti-CD19), A20 (anti-CD20), MN-14 (anti-CEACAM5), MN-15 (anti-CEACAM6), MN-3 (anti-CEACAM6), R1 (anti-IGF-1R), Mu-9 (anti-CSAp), Immu 31 (anti-AFP), CC49 (anti-TAG-72), J591 (anti-PSMA), HuJ591 (anti-PSMA), AB-PG1-XG1-026 (anti-PSMA dimer), D2/B (anti-PSMA), G250 (anti-carbonic anhydrase IX) and hL243 (anti-HLA-DR).']},
   {'claim_text': ['22. The method of claim 9 , wherein the antibody or antibody fragment binds to an antigen selected from the group consisting of carbonic anhydrase IX, alpha-fetoprotein (AFP), α-actinin-4, ART-4, B7, Ba 733, BAGE, BrE3-antigen, CA125, CAMEL, CAP-1, CASP-8/m, CCL19, CCL21, CD1, CD1a, CD2, CD3, CD4, CD5, CD8, CD11A, CD14, CD15, CD16, CD18, CD19, CD20, CD21, CD22, CD23, CD25, CD29, CD30, CD32b, CD33, CD37, CD38, CD40, CD40L, CD44, CD45, CD46, CD52, CD54, CD55, CD59, CD64, CD66a-e, CD67, CD70, CD70L, CD74, CD79a, CD80, CD83, CD95, CD126, CD132, CD133, CD138, CD147, CD154, CDC27, CDK-4/m, CDKN2A, CTLA-4, CXCR4, CXCR7, CXCL12, HIF-1α, colon-specific antigen-p (CSAp), CEACAM5, CEACAM6, c-Met, DAM, EGFR, EGFRvIII, EGP-1 (TROP-2), EGP-2, ELF2-M, Ep-CAM, fibroblast growth factor (FGF), Flt-1, Flt-3, folate receptor, G250 antigen, GAGE, gp100, GRO-β, H2B, H3, H4, HLA-DR, HM1.24, human chorionic gonadotropin (HCG), HER2/neu, HMGB-1, hypoxia inducible factor (HIF-1), HSP70-2M, HST-2, Ia, IGF-1R, IFN-γ, IFN-α, IFN-β, IFN-λ, IL-4R, IL-6R, IL-13R, IL-15R, IL-17R, IL-18R, IL-2, IL-6, IL-8, IL-12, IL-15, IL-17, IL-18, IL-23, IL-25, insulin-like growth factor-1 (IGF-1), KS1-4, Le-Y, LDR/FUT, macrophage migration inhibitory factor (MIF), MAGE, MAGE-3, MART-1, MART-2, NY-ESO-1, TRAG-3, mCRP, MCP-1, MIP-1A, MIP-1B, MIF, MUC1, MUC2, MUC3, MUC4, MUC5ac, MUC13, MUC16, MUM-1/2, MUM-3, NCA66, NCA95, NCA90, PD-1, PD-L1, PD-1 receptor, placental growth factor, p53, PLAGL2, prostatic acid phosphatase, PSA, PRAME, PSMA, P1GF, ILGF, ILGF-1R, IL-6, IL-25, RS5, RANTES, T101, SAGE, S100, survivin, survivin-2B, TAC, TAG-72, tenascin, TRAIL receptors, TNF-α, Tn antigen, Thomson-Friedenreich antigen, tumor necrosis antigens, VEGFR, ED-B fibronectin, WT-1, 17-1A-antigen, complement factors C3, C3a, C3b, C5a, C5, bc1-2, bc1-6, Kras, and an oncogene product.']}],
  'lang': 'en'}]

In [190]:
#Though it's US jurisdiction, for sanity, just double checking that language is english for all
langs = df["claims"].apply(
    lambda x: x[0].get("lang") if isinstance(x, list) and len(x) > 0 else None
)
langs.value_counts(dropna=False)

claims
en      2322
None       9
Name: count, dtype: int64

In [191]:
# So the Claim column is a list but contains one dictionary, with keys of claims and language. 
# In that claims key, the value is another list of claim dictionaries where each has the key of claim_text and the value is the text
# This column is nested and odd looking.

# I'm just gonna extract ALL claim text into a per row, so flatten it:
def extract_all_claim_text(claim_obj):
    if not isinstance(claim_obj, list) or len(claim_obj) == 0: 
        return "" #For the 9 rows that don't have a list in their claims column (are float, NaN), just return an empty string
    
    claim_block = claim_obj[0]  # Take that first dictionary in [{ "claims": [...], "lang": "en" }]
    
    if "claims" not in claim_block: #just in case, confirm claims key exists
        return ""
    
    full_text = [] #initiate list
    
    for claim in claim_block["claims"]: #inside the list in the dictionary, [{[ ]}]
        text_parts = claim.get("claim_text", []) #grab the value of claim_text key. Return [] if key doesn't exist
        if isinstance(text_parts, list): #if text_parts we grabbed is a list (should be), then
            full_text.append(" ".join(text_parts)) #glue all items in list into one string, with space in between
    
    return " ".join(full_text) #combine all claims text

In [192]:
df["claims_text"] = df["claims"].apply(extract_all_claim_text)

In [193]:
df["claims_text"].iloc[0]

"1. A method to produce a compound, CL2A-SN-38, of the structure, comprising performing a reaction scheme as shown: further comprising reacting SN-38 with tert-butyldimethylsilsl chloride (TBDMS-Cl) to produce 10-O-TBDMS-SN-38 (intermediate 4), wherein the reaction is carried out in dichloromethane solvent. 2. The method of claim 1 , further comprising reacting 10-O-TBDMS-SN-38 (intermediate 4) with triphosgene and DMAP to make 10-O-TBDMS-SN-38-20-O-chloroformate (reactive intermediate 5), wherein the reaction is performed by adding triphosgene to a dichloromethane reaction mixture that contains intermediate 4, and the triphosgene is added in portions, to reduce exothermic reaction during large scale manufacture and maintain high reaction yield. 3. The method of claim 1 , further comprising precipitating Lys(MMT)-PABOH (intermediate 2) with heptane. 4. The method of claim 3 , further comprising assaying residual diethylamine in the precipitated intermediate 2 and purifying the precipitate by chromatography if the presence of diethylamine was detected. 5. The method of claim 1 , further comprising reacting azido-PEG-Lys(MMT)-PABO-CO-20-O-SN-38 (intermediate 7) with MCC-Yne (intermediate 8) by a copper catalyzed cycloaddition reaction to make MCC-PEG-Lys(MMT)-PABO-CO-20-O-SN-38 (intermediate 9), wherein the reaction is carried out for 14 h to improve product yield. 6. The method of claim 5 , wherein intermediate 9 is first purified by silica gel chromatography, followed by extraction with EDTA to remove copper. 7. The method of claim 1 , further comprising reacting a maleimide moiety of CL2A-SN38 with a protein or peptide to make an SN38-conjugated protein or peptide. 8. The method of claim 7 , wherein the maleimide moiety reacts with a reduced sulfhydryl on the protein or peptide. 9. The method of claim 7 , wherein the protein or peptide is an antibody or an antigen-binding antibody fragment and the SN-38 conjugated antibody or antibody fragment is an immunoconjugate. 10. The method of claim 9 , further comprising purifying the immunoconjugate by tangential flow filtration (TFF). 11. The method of claim 9 , wherein the TFF is performed with a 50,000 Dalton molecular weight cut-off membrane using 25- to 30-diafiltration volumes of buffer. 12. The method of claim 11 , further comprising formulating the immunoconjugate in Good's biological buffer at a pH of 6.0 to 7.0, and lyophilizing the immunoconjugate for storage. 13. The method of claim 12 , wherein the Good's biological buffer is selected from the group consisting of 2-(N-morpholino)ethanesulfonic acid (MES), 3-(N-morpholino)propanesulfonic acid (MOPS), 4-(2-hydroxyethyl)piperazine-1-ethanesulfonic acid (HEPES), and 1,4-piperazinediethanesulfonic acid (PIPES), in the pH range of 6-7, preferably in the pH range of 6.5 to 7, and at a buffer concentration of 10-100 mM, preferably 25 mM. 14. The method of claim 13 , wherein the buffer is 25 mM MES buffer, pH 6.5. 15. The method of claim 9 , wherein the antibody is a bispecific antibody or a monoclonal antibody. 16. The method of claim 9 , wherein the antibody fragment is selected from the group consisting of F(ab′) 2 , F(ab) 2 , Fab′, Fab, Fv, scFv, single domain antibody and half-molecule of IgG4 antibody. 17. The method of claim 9 , wherein the antibody or antibody fragment is attached to between 1 and 12 copies of CL2A-SN38. 18. The method of claim 9 , wherein the antibody or antibody fragment is attached to 6 copies of CL2A-SN38. 19. The method of claim 9 , wherein the antibody or antibody fragment is attached to between 1 and 5 copies of CL2A-SN38. 20. The method of claim 9 , wherein the antibody is an anti-cancer antibody, an anti-infectious disease antibody, or an anti-autoimmune disease antibody. 21. The method of claim 9 , wherein the antibody is selected from the group consisting of LL1 (anti-CD74), LL2 (anti-CD22), RFB4 (anti-CD22), RS7 (anti-EGP-1), PAM4 (anti-MUC5AC), KC4 (anti-mucin), A19 (anti-CD19), A20 (anti-CD20), MN-14 (anti-CEACAM5), MN-15 (anti-CEACAM6), MN-3 (anti-CEACAM6), R1 (anti-IGF-1R), Mu-9 (anti-CSAp), Immu 31 (anti-AFP), CC49 (anti-TAG-72), J591 (anti-PSMA), HuJ591 (anti-PSMA), AB-PG1-XG1-026 (anti-PSMA dimer), D2/B (anti-PSMA), G250 (anti-carbonic anhydrase IX) and hL243 (anti-HLA-DR). 22. The method of claim 9 , wherein the antibody or antibody fragment binds to an antigen selected from the group consisting of carbonic anhydrase IX, alpha-fetoprotein (AFP), α-actinin-4, ART-4, B7, Ba 733, BAGE, BrE3-antigen, CA125, CAMEL, CAP-1, CASP-8/m, CCL19, CCL21, CD1, CD1a, CD2, CD3, CD4, CD5, CD8, CD11A, CD14, CD15, CD16, CD18, CD19, CD20, CD21, CD22, CD23, CD25, CD29, CD30, CD32b, CD33, CD37, CD38, CD40, CD40L, CD44, CD45, CD46, CD52, CD54, CD55, CD59, CD64, CD66a-e, CD67, CD70, CD70L, CD74, CD79a, CD80, CD83, CD95, CD126, CD132, CD133, CD138, CD147, CD154, CDC27, CDK-4/m, CDKN2A, CTLA-4, CXCR4, CXCR7, CXCL12, HIF-1α, colon-specific antigen-p (CSAp), CEACAM5, CEACAM6, c-Met, DAM, EGFR, EGFRvIII, EGP-1 (TROP-2), EGP-2, ELF2-M, Ep-CAM, fibroblast growth factor (FGF), Flt-1, Flt-3, folate receptor, G250 antigen, GAGE, gp100, GRO-β, H2B, H3, H4, HLA-DR, HM1.24, human chorionic gonadotropin (HCG), HER2/neu, HMGB-1, hypoxia inducible factor (HIF-1), HSP70-2M, HST-2, Ia, IGF-1R, IFN-γ, IFN-α, IFN-β, IFN-λ, IL-4R, IL-6R, IL-13R, IL-15R, IL-17R, IL-18R, IL-2, IL-6, IL-8, IL-12, IL-15, IL-17, IL-18, IL-23, IL-25, insulin-like growth factor-1 (IGF-1), KS1-4, Le-Y, LDR/FUT, macrophage migration inhibitory factor (MIF), MAGE, MAGE-3, MART-1, MART-2, NY-ESO-1, TRAG-3, mCRP, MCP-1, MIP-1A, MIP-1B, MIF, MUC1, MUC2, MUC3, MUC4, MUC5ac, MUC13, MUC16, MUM-1/2, MUM-3, NCA66, NCA95, NCA90, PD-1, PD-L1, PD-1 receptor, placental growth factor, p53, PLAGL2, prostatic acid phosphatase, PSA, PRAME, PSMA, P1GF, ILGF, ILGF-1R, IL-6, IL-25, RS5, RANTES, T101, SAGE, S100, survivin, survivin-2B, TAC, TAG-72, tenascin, TRAIL receptors, TNF-α, Tn antigen, Thomson-Friedenreich antigen, tumor necrosis antigens, VEGFR, ED-B fibronectin, WT-1, 17-1A-antigen, complement factors C3, C3a, C3b, C5a, C5, bc1-2, bc1-6, Kras, and an oncogene product."

In [194]:
(df["claims_text"] == "").sum()
#So all 2322 rows were flattened, and original 9 NaN rows are empty

9

In [195]:
#Just checking how much text these claims text will contain
df["claims_text"].str.len().describe()

count      2331.000000
mean       9635.889318
std       11887.840847
min           0.000000
25%        3614.500000
50%        5964.000000
75%       11138.000000
max      178120.000000
Name: claims_text, dtype: float64

In [196]:
#As this is going to be inputted into the model via OpenAI's API, need to ensure not too large
df["claims_text"].str.len().sum()

22461258

In [197]:
empty_claims = df[df["claims_text"] == ""] #grab those 9 empty claim rows

In [198]:
empty_claims[["lens_id", "kind", "legal_status"]]

,lens_id,kind,legal_status
417,032-240-698-890-336,A1,{'calculation_log': ['Application Filing Date:...
431,053-807-865-739-075,A1,{'calculation_log': ['Application Filing Date:...
798,029-853-159-129-12X,A1,{'calculation_log': ['Application Filing Date:...
1042,022-873-617-525-132,A1,"{'granted': True, 'grant_date': '2015-05-12', ..."
1212,058-165-013-366-539,A1,{'calculation_log': ['Application Filing Date:...
1421,184-270-747-563-446,B2,"{'granted': True, 'grant_date': '2025-12-23', ..."
1718,196-857-624-941-935,A1,{'calculation_log': ['Application Filing Date:...
2197,013-287-333-155-311,A1,"{'granted': True, 'grant_date': '2025-10-28', ..."
2327,098-651-403-196-496,A1,{'calculation_log': ['Application Filing Date:...

These are patents, so claims should not be empty
- Looking in The Lens, claims information is "currently unavailable" for these 9 patents
- So will manually fill in, as just 9, using Google Patents

In [199]:
#For easier searching, will grab the title
row = empty_claims.iloc[0]
row["biblio"]

{'publication_reference': {'jurisdiction': 'US',
  'doc_number': '20230075822',
  'kind': 'A1',
  'date': '2023-03-09'},
 'application_reference': {'jurisdiction': 'US',
  'doc_number': '202117904677',
  'kind': 'A',
  'date': '2021-02-19'},
 'application_number': '17/904,677',
 'priority_claims': {'claims': [{'jurisdiction': 'US',
    'doc_number': '202117904677',
    'kind': 'A',
    'date': '2021-02-19',
    'sequence': 1},
   {'jurisdiction': 'US',
    'doc_number': '202062979327',
    'kind': 'P',
    'date': '2020-02-20',
    'sequence': 2},
   {'jurisdiction': 'CA',
    'doc_number': '2021050183',
    'kind': 'W',
    'date': '2021-02-19',
    'sequence': 3}],
  'earliest_claim': {'date': '2020-02-20'}},
 'invention_title': [{'text': 'USE OF CASTALAGIN OR ANALOGS THEREOF FOR ANTI-CANCER EFFICACY AND TO INCREASE THE RESPONSE TO IMMUNE CHECKPOINT INHIBITORS',
   'lang': 'en'}],
 'parties': {'applicants': [{'residence': 'CA',
    'extracted_name': {'value': 'THE ROYAL INSTITUTION FOR THE ADVANCEMENT OF LEARNING/MCGILL UNIV'}},
   {'residence': 'CA', 'extracted_name': {'value': 'UNIV LAVAL'}},
   {'residence': 'CA', 'extracted_name': {'value': 'VAL CHUM LP'}}],
  'inventors': [{'residence': 'CA',
    'sequence': 1,
    'extracted_name': {'value': 'ROUTY BERTRAND'}},
   {'residence': 'CA',
    'sequence': 2,
    'extracted_name': {'value': 'MARETTE ANDRÉ'}},
   {'residence': 'CA',
    'sequence': 3,
    'extracted_name': {'value': 'MESSAOUDENE MERIEM'}},
   {'residence': 'CA',
    'sequence': 4,
    'extracted_name': {'value': 'CASTAGNER BASTIEN'}},
   {'residence': 'CA',
    'sequence': 5,
    'extracted_name': {'value': 'PIDGEON REILLY'}}],
  'owners_all': [{'recorded_date': '2023-09-21',
    'execution_date': '2022-08-16',
    'extracted_name': {'value': 'VAL-CHUM LIMITED PARTNERSHIP'},
    'extracted_address': '1405 BOULEVARD DU PARC-TECHNOLOGIQUE, QUEBEC, G1P 4P5',
    'extracted_country': 'CA'},
   {'recorded_date': '2023-09-21',
    'execution_date': '2022-05-18',
    'extracted_name': {'value': "CENTRE HOSPITALIER DE L'UNIVERSITE DE MONTREAL"},
    'extracted_address': '850 RUE ST-DENIS, PAVILLON S, MONTREAL, H2X 0A9',
    'extracted_country': 'CA'},
   {'recorded_date': '2023-09-21',
    'execution_date': '2021-02-19',
    'extracted_name': {'value': 'UNIVERSITE LAVAL'},
    'extracted_address': "2325 RUE DE L'UNIVERSITE, QUEBEC, G1V 0A6",
    'extracted_country': 'CA'},
   {'recorded_date': '2023-09-21',
    'execution_date': '2022-05-25',
    'extracted_name': {'value': 'THE ROYAL INSTITUTION FOR THE ADVANCEMENT OF LEARNING/MCGILL UNIVERSITY'},
    'extracted_address': '845 SHERBROOKE STREET WEST, MONTREAL, H3A 0G4',
    'extracted_country': 'CA'}]},
 'classifications_ipcr': {'classifications': [{'symbol': 'A61K31/365',
    'classification_value': 'I',
    'classification_symbol_position': 'F'},
   {'symbol': 'A61K39/395',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61P35/00',
    'classification_value': 'I',
    'classification_symbol_position': 'L'}]},
 'classifications_cpc': {'classifications': [{'symbol': 'A61K9/48',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/37',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K36/61',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K39/395',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61P35/00',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61P37/02',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07D493/22',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K2317/76',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/2818',
    'classification_value': 'I',
    'classification_symbol_position': 'F'},
   {'symbol': 'A61P35/00',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/365',
    'classification_value': 'I',
    'classification_symbol_position': 'F'},
   {'symbol': 'A61K39/3955',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K2039/505',
    'classification_value': 'A',
    'classification_symbol_position': 'L'}]},
 'cited_by': {}}

In [200]:
#So title is in invention_title

#Grab the title using it:
empty_titles = empty_claims.apply(
    lambda row: row["biblio"].get("invention_title", [{}])[0].get("text")
    if isinstance(row["biblio"], dict)
    else None,
    axis=1
)

In [201]:
#To search on google patents, also easier to get document number and not lens-id
def get_pub_number(biblio):
    if not isinstance(biblio, dict):
        return None
    
    pub = biblio.get("publication_reference", {})
    
    jurisdiction = pub.get("jurisdiction")
    doc_number = pub.get("doc_number")
    kind = pub.get("kind")
    
    if jurisdiction and doc_number and kind:
        return f"{jurisdiction}{doc_number}{kind}"

    return None


empty_pub_numbers = empty_claims["biblio"].apply(get_pub_number)

pd.set_option("display.max_colwidth", None) #resest with pd.reset_option("display.max_colwidth")

pd.DataFrame({
    "lens_id": empty_claims["lens_id"],
    "publication_number": empty_pub_numbers,
    "title": empty_titles
})

,lens_id,publication_number,title
417,032-240-698-890-336,US20230075822A1,USE OF CASTALAGIN OR ANALOGS THEREOF FOR ANTI-CANCER EFFICACY AND TO INCREASE THE RESPONSE TO IMMUNE CHECKPOINT INHIBITORS
431,053-807-865-739-075,US20230073248A1,COMPOSITIONS AND METHODS FOR INDUCING IMMUNE TOLERANCE IN TRANSPLANTATION RECIPIENTS
798,029-853-159-129-12X,US20230075925A1,NON-PERIPHERAL QUATERNARY AMMONIUM-MODIFIED ZINC PHTHALOCYANINE AND PREPARATION METHOD AND USE THEREOF
1042,022-873-617-525-132,US20120190622A1,INHIBITORS OF THE EPIDERMAL GROWTH FACTOR RECEPTOR-HEAT SHOCK PROTEIN 90 BINDING INTERACTION
1212,058-165-013-366-539,US20230075779A1,METHODS AND COMPOSITIONS FOR TREATING CANCER OR VIRAL INFECTION WITH A PLA2G2D ANTAGONIST
1421,184-270-747-563-446,US12503518B2,Heparanase-neutralizing A54 monoclonal antibody
1718,196-857-624-941-935,US20230074657A1,"ANTI-LAG3 MONOCLONAL ANTIBODY, AND PREPARATION METHOD THEREFOR AND USE THEREOF"
2197,013-287-333-155-311,US20230076371A1,PHARMACEUTICAL COMPOSITION AND USE THEREOF
2327,098-651-403-196-496,US20230074385A1,METHOD FOR PRODUCING ERIBULIN-BASED ANTIBODY-DRUG CONJUGATE

So I searched the publication_number on Google Patents, cross checked with title
- Then copy over their claims to the variables below

In [87]:
claim_text_032_240_698_890_336 = "1. A method for treating a subject suffering from a cancer resistant to immunotherapy comprising administering to the subject a therapeutically effective amount of castalagin or an analog thereof. 2. The method of claim 1, wherein the immunotherapy comprises immune checkpoint inhibitor therapy. 3. The method of claim 2, wherein the immune checkpoint inhibitor is a Programmed cell death-1 (PD-1) inhibitor, a cytotoxic T-lymphocyte-associated antigen 4 (CTLA-4) inhibitor, or a Programmed death-ligand 1 (PD-L1) inhibitor. 4. (canceled) 5. The method of claim 3 [[or 4]], wherein the immune checkpoint inhibitor is an anti-PD-1 blocking antibody. 6. The method of claim 1, wherein the castalagin. 7. (canceled) 8. The method of claim 1, wherein the method comprises administering a pharmaceutical composition comprising castalagin. 9. The method of claim 1, wherein the castalagin or analog thereof is formulated for delivery of the castalagin or analog thereof into the intestines. 10. (canceled) 11. The method of claim 1, wherein the cancer is lung cancer or breast cancer. 12. The method of claim 11, wherein the lung cancer is non-small cell lung cancer (NSCLC), and wherein the breast cancer is triple-negative breast cancer (TNBC). 13. (canceled) 14. The method of claim 1, further comprising administering an effective amount of the immune checkpoint inhibitor to the subject. 15. A method for enhancing the anti-tumor immune response in a subject suffering from cancer, the method comprising administering to the subject a therapeutically effective amount of castalagin or an analog thereof. 16. The method of claim 15, wherein the anti-tumor immune response is the anti-tumor T-cell response. 17. The method of claim 15, wherein the method further comprising administering a therapeutically effective amount of an immune checkpoint inhibitor to the subject. 18. The method of claim 17, wherein the immune checkpoint inhibitor is a Programmed cell death-1 (PD-1) inhibitor, a cytotoxic T-lymphocyte-associated antigen 4 (CTLA-4) inhibitor, or a Programmed death-ligand 1 (PD-L1) inhibitor. 19. (canceled) 20. The method of claim 18, wherein the immune checkpoint inhibitor is an anti-PD-1 blocking antibody. 21. The method of claim 15, wherein the castalagin or analog thereof is present in a plant or fruit extract. 22. (canceled) 23. The method of claim 15, wherein the method comprises administering a pharmaceutical composition comprising castalagin. 24. The method of claim 15, wherein the castalagin or analog thereof is formulated for delivery of the castalagin or analog thereof into the intestines. 25. (canceled) 26. The method of claim 15, wherein the cancer is lung cancer or breast cancer. 27. The method of claim 26, wherein the lung cancer is non-small cell lung cancer (NSCLC), and wherein the breast cancer is triple-negative breast cancer (TNBC). 28-57. (canceled)"
claim_text_053_807_865_739_075 = "What is claimed is: 1. A method of inducing allograft tolerance in a recipient subject comprising: administering prior to donor organ or tissue transplantation in the subject, a pharmaceutical composition comprising one or more anti-CD3 immunotoxin and a pharmaceutical composition comprising peripheral blood cells obtained from the donor of the donor organ or tissue and inducing allograft tolerance in the recipient subject to the donor organ. 2. The method according to claim 1, wherein administering the pharmaceutical composition comprising peripheral blood cells obtained from the donor comprises infusing the peripheral blood cell composition into the subject. 3. The method according to claim 1, wherein administering the pharmaceutical composition comprising peripheral blood cells obtained from the donor comprises administering the peripheral blood cell composition before, during, simultaneously, and/or after administering the pharmaceutical composition comprising the anti-CD3 immunotoxin to the subject. 4. The method according to claim 1, further comprising transplanting a solid organ, tissue or cells from the donor into the recipient. 5. The method according to claim 4, wherein the donor solid organ, donor tissue, or donor cells comprise kidney, heart, lung, liver, intestine, pancreas, skin, vascular composite allografts (VCAs), leukocytes, hepatocytes, pancreatic islets, corneal epithelial cells, bone marrow (hematopoietic stem cells, HCT) or a combination thereof. 6. The method according to claim 4, further comprising assessing allo-antibody or anti-donor antibody production in the subject before, during and/or after transplantation of the donor solid organ or tissue into the recipient. 7. The method according to claim 1, further comprising administering an immunosuppressant to the subject. 8. The method according to claim 4, wherein the transplanting of the donor solid organ or donor tissue comprises transplanting the donor solid organ or donor tissue at a time when both T cells and B cells are repressed. 9. (canceled) 10. The method according to claim 1, wherein administering the peripheral donor blood cells to the subject occurs with minimal to no peripheral donor blood cell engraftment. 11. The method according to claim 1, wherein the anti-CD3 immunotoxin comprises a recombinant fusion toxin. 12. The method according to claim 11, wherein the recombinant fusion toxin comprises an anti-human CD3 binding domain and a truncated diphtheria toxin. 13. The method according to claim 12, wherein the anti-human CD3 binding domain comprises an anti-human CD3 epsilon specific monoclonal antibody and the truncated diphtheria toxin comprises a translocation and a catalytic domain of a truncated diphtheria toxin. 14. The method according to claim 7, wherein the immunosuppressant comprises one or more of a steroid, Janus kinase inhibitors, calcineurin inhibitors, mTOR inhibitors, IMDH inhibitors, polyclonal antibodies, and monoclonal antibodies. 15. The method according to claim 14, wherein the immunosuppressant comprises one or more immunosuppressant comprising prednisone (e.g. Deltasone, Orasone), budesonide (Entocort EC), prednisolone (Millipred), tofacitinib (Xeljanz), cyclosporine (Neoral, Sandimmune, SangCya), tacrolimus (Astagraf XL, Envarsus XR, Prograf), sirolimus (Rapamune), everolimus (Afinitor, Zortress), azathioprine (Azasan, Imuran), leflunomide (Arava), mycophenolate (CellCept, Myfortic), abatacept (Orencia), adalimumab (Humira), anakinra (Kineret), certolizumab (Cimzia), etanercept (Enbrel), golimumab (Simponi), infliximab (Remicade), ixekizumab (Taltz), natalizumab (Tysabri), rituximab (Rituxan), secukinumab (Cosentyx), tocilizumab (Actemra), ustekinumab (Stelara), vedolizumab (Entyvio), basiliximab (Simulect), daclizumab or (Zinbryta). 16. The method according to claim 14, wherein the immunosuppressant comprises one or more of tacrolimus, mycophenolate and a steroid. 17. The method according to claim 1, wherein MHC compatibility of donor and recipient is selected from fully MHC-matched, haplo-mismatched, or fully mismatched. 18. The method according to claim 1, 2 of 3, wherein the peripheral donor blood cells are obtained without at least one of cytokine mobilization and stem cell enrichment. 19. (canceled) 20. A pharmaceutical composition comprising, one or more anti-CD3 immunotoxin; and peripheral blood cells obtained from a donor of an organ. 21. (canceled) 22. A kit comprising the pharmaceutical composition according to claim 20; and at least one container. 23. A method for depleting T cells in organs and tissues of a subject comprising administering one or more anti-CD3 immunotoxin to a subject in need of such a treatment. 24. (canceled) 25. The method according to claim 23, wherein the subject has GvHD. 26-28. (canceled)"
claim_text_029_853_159_129_12X = "1. A non-peripheral quaternary ammonium-modified zinc phthalocyanine, having a structural formula shown as follows: Figure US20230075925A1-20230309-C00007 2. A preparation method of the non-peripheral quaternary ammonium-modified zinc phthalocyanine according to claim 1, comprising the following steps: conducting a reaction on 1-[4-(aminoethyl)phenoxy] zinc phthalocyanine and methyl iodide as reactants in N,N-dimethylformamide as a solvent under the protection of nitrogen at 0° C. to a room temperature for 5 h to 50 h; and removing impurities by solvent cleaning and column chromatography isolation to obtain 1-[4-(N,N,N-trimethyl-2-aminoethyl)phenoxy] zinc phthalocyanine iodide. 3. The preparation method according to claim 2, wherein the 1-[4-(aminoethyl)phenoxy] zinc phthalocyanine and the methyl iodide have a mass ratio of 1:(50-200). 4. The preparation method according to claim 2, wherein 1 mg of the 1-[4-(aminoethyl)phenoxy] zinc phthalocyanine requires 0.3 mL to 3 mL of the N,N-dimethylformamide. 5. A preparation method of a photodynamic drug or a photosensitizer comprising using the non-peripheral quaternary ammonium-modified zinc phthalocyanine according to claim 1. 6. The preparation method according to claim 5, wherein the non-peripheral quaternary ammonium-modified zinc phthalocyanine is capable of inhibiting a distal tumor in combination with an immune checkpoint blocker PD-L1 antibody. 7. The preparation method according to claim 5, wherein the photosensitizer or the photodynamic drug prepared by the non-peripheral quaternary ammonium-modified zinc phthalocyanine is capable of treating a tumor in combination with an immune checkpoint blocker. 8. The preparation method according to claim 5, wherein the photodynamic drug or the photosensitizer is used for a photodynamic therapy (PDT), photodynamic diagnosis, or photodynamic disinfection. 9. The preparation method according to claim 8, wherein the PDT comprises a PDT of a malignant tumor, a PDT of a benign tumor, an in vitro photodynamic purification therapy of leukemia, or a PDT of a non-cancer disease. 10. The preparation method according to claim 9, wherein the non-cancer disease comprises a bacterial infection, an oral disease, a macular degeneration-caused eye disease, arteriosclerosis, a traumatic infection, a skin disease, or a viral infection. 11. The preparation method according to claim 8, wherein the photodynamic disinfection comprises photodynamic sterilization and purification of blood or a blood derivative, photodynamic sterilization and disinfection of water, and photodynamic disinfection of a medical or household appliance. 12-20. (canceled) 21. The preparation method according to claim 7, wherein the photodynamic drug or the photosensitizer is used for a photodynamic therapy (PDT), photodynamic diagnosis, or photodynamic disinfection. 22. The preparation method according to claim 21, wherein the PDT comprises a PDT of a malignant tumor, a PDT of a benign tumor, an in vitro photodynamic purification therapy of leukemia, or a PDT of a non-cancer disease. 23. The preparation method according to claim 22, wherein the non-cancer disease comprises a bacterial infection, an oral disease, a macular degeneration-caused eye disease, arteriosclerosis, a traumatic infection, a skin disease, or a viral infection. 24. The preparation method according to claim 21, wherein the photodynamic disinfection comprises photodynamic sterilization and purification of blood or a blood derivative, photodynamic sterilization and disinfection of water, and photodynamic disinfection of a medical or household appliance."
claim_text_022_873_617_525_132 = "1. A composition comprising a compound that inhibits a binding interaction between an epidermal growth factor receptor (EGFR) and a heat shock protein 90 (HSP90). 2. The composition of claim 1, wherein the compound is a peptide or peptide analog. 3. (canceled) 4. The composition of claim 2, wherein the compound comprises 4 to 10 consecutive amino acids of amino acids 688 to 955 of SEQ ID NO: 1. 5. The composition of claim 4, wherein the compound comprises 4 to 10 consecutive amino acids from amino acids 761-781 of the EGFR. 6. The composition of claim 5, wherein the compound comprises the amino acid sequence DNPH (SEQ ID NO: 13) or RLLGIC (SEQ ID NO: 14). 7. The composition of claim 6, wherein the compound comprises the amino acid sequence SVDNPH (SEQ ID NO: 15), or SVDNPHV (SEQ ID NO: 16), or SVDNPHVX (SEQ ID NO: 17), wherein X is C, S, G, V, or A. 8. The composition of claim 2, wherein the compound comprises an amino acid sequence of SVDNPH (SEQ ID NO: 15) with up to two amino acid substitutions. 9. The composition of claim 8, wherein the amino acid substitution(s) occur(s) at one or two of the positions 1, 3, and 5 of SVDNPH (SEQ ID NO: 15). 10.-12. (canceled) 13. The composition of any of claim 8, wherein the peptide or peptidomimetic comprises an amino acid sequence selected from the group consisting of: AVDNPH, (SEQ ID NO: 25) DVDNPH, (SEQ ID NO: 26) IVDNPH, (SEQ ID NO: 27) SVGNPH, (SEQ ID NO: 28) SVDNGH, (SEQ ID NO: 29) and SVAAPH. (SEQ ID NO: 30) 14. The composition of any of claim 2, comprising an intramolecular bridge which covalently links the side chains of two amino acids of the compound. 15.-21. (canceled) 22. The composition of claim 14, comprising the amino acid sequence XDNPHX (SEQ ID NO: 32), wherein the side chains of the amino acids at positions 1 and 6 are covalently linked by the intramolecular bridge. 23.-25. (canceled) 26. The composition of any of claim 22, comprising the amino acid sequence SXDNPHXX (SEQ ID NO: 33), wherein the X at position 8 is C, S, G, V, or A. 27.-29. (canceled) 30. The composition of any of claim 2, wherein the peptide or peptide analog is fused to a cell penetrating peptide (CPP). 31. (canceled) 32. The composition of any of claim 2, comprising a peptide delivery agent. 33.-39. (canceled) 40. The composition of claim 1, comprising a pharmaceutically acceptable carrier, diluents, or excipient. 41. (canceled) 42. A method of treating cancer in a subject comprising administering to the subject a composition of claim 40 in an amount effective to treat the cancer. 43. The method of claim 42, wherein the cancer is characterized by overexpression of EGFR or expression of a mutant EGFR. 44.-49. (canceled) 50. A method of sensitizing tumors to radiation therapy, chemotherapy, or a combination thereof, in a subject, comprising administering to the subject a composition of any of claim 1 in an amount effective to sensitize the tumors to the therapy. 51.-53. (canceled) 54. A kit comprising the composition of claim 1 in combination with an agent used in radiation therapy or chemotherapy. 55.-64. (canceled)"
claim_text_058_165_013_366_539 = "1. A method of treating a cancer or viral infection in an individual, comprising administering into the individual an effective amount of an antagonist targeting PLA2G2D signaling pathway. 2. The method of claim 1, wherein the antagonist is an antagonist inhibits or downregulates PLA2G2D. 3. The method of claim 2, wherein the PLA2G2D is a human PLA2G2D. 4. The method of claim 2 or claim 3, wherein the antagonist decreases enzymatic activity level of PLA2G2D. 5. The method of claim 4, wherein the antagonist targeting PLA2G2D signaling pathway blocks a catalytic site on PLA2G2D. 6. The method of claim 5, wherein the antagonist targets the H67 catalytic site on a human PLA2G2D according to SEQ ID NO: 1 or 5. 7. The method of any one of claims 1-3, wherein the antagonist comprises a siRNA, an miRNA, an antisense RNA, or a gene editing system. 8. The method of any one of claims 1-3, wherein the antagonist blocks the binding of PLA2G2D to an immune cell. 9. The method of claim 8, wherein the immune cell is a T cell. 10. The method of any one of claims 1-3, wherein the antagonist comprises an anti-PLA2G2D antibody. 11. The method of claim 10, wherein the anti-PLA2G2D antibody is a monoclonal antibody. 12. The method of claim 10, wherein the antagonist is a fusion protein or immunoconjugate further comprising a second moiety. 13. The method of claim 12, wherein the second moiety comprises a cytokine. 14. The method of any one of claims 1-3, wherein the antagonist comprises an inhibitory PLA2G2D polypeptide that blocks the binding of PLA2G2D to an immune cell. 15. The method of claim 14, wherein the inhibitory PLA2G2D polypeptide binds to the immune cell with a greater affinity than a wildtype PLA2G2D. 16. The method of claim 15, wherein the immune cells is a T cell. 17. The method of any one of claims 14-16, wherein inhibitory PLA2G2D polypeptide further comprises a stabilizing domain. 18. The method of claim 17, wherein the stabilizing domain is an Fc domain. 19. The method of any one of claims 14-18, wherein the inhibitory PLA2G2D polypeptide has a length of about 50 to about 200 amino acids. 20. The method of any one of claims 14-19, wherein the inhibitory PLA2G2D polypeptide has a) a mutation at a position corresponding to histidine at position 67 (H67) according to SEQ ID NO: 1 or 5 or b) a mutation at the position corresponding to glycine at position 80 (G80) according to SEQ ID NO: 5. 21. The method of claim 20, wherein the inhibitory PLA2G2D polypeptide comprises an amino acid sequence selected from the group consisting of SEQ ID NOs: 3, 4, and 7-12 or a variant thereof. 22. The method of any one of claims 1-21, wherein the disease or condition is a cancer. 23. The method of claim 22, wherein the cancer is a solid tumor. 24. The method of claim 22 or claim 23, wherein the cancer is an advanced or malignant tumor. 25. The method of any one of claims 22-24, wherein the cancer has an increased expression level of PLA2G2D. 26. The method of any one of claims 22-25, wherein the cancer is selected from the group consisting of lung cancer, breast cancer, liver cancer, gastric cancer, cervical cancer, endometrial cancer, thyroid cancer, colorectal cancer, head and neck cancer, pancreatic cancer, renal cancer, prostate cancer, urothelial cancer, testis cancer, ovarian cancer and melanoma. 27. The method of any one of claims 1-21, wherein the disease or condition is a viral infection. 28. The method of claim 27, wherein the expression level of PLA2G2D at an infected site is higher than that of an uninfected site. 29. The method of any one of claims 1-28, wherein the method further comprises administering a second agent. 30. The method of claim 29, wherein the second agent is selected from the group consisting of a chemotherapeutic agent, an immunomodulator, an anti-angiogenesis agent, a growth inhibitory agent, and an antineoplastic agent. 31. The method of claim 30, wherein the second agent is an immunomodulator. 32. The method of claim 31, wherein the immunomodulator is an immune checkpoint inhibitor. 33. The method of claim 28, wherein the immune checkpoint inhibitor specifically target PD-L1, PD-L2, CTLA4, PD-L2, PD-1, CD47, TIGIT, GITR, TIM3, LAG3, CD27, 4-1BB, or B7H4. 34. The method of claim 33, wherein the second agent comprises a cell comprising a chimeric antigen receptor that specifically binds to a tumor antigen. 35. The method of any one of claims 29-34, wherein the antagonist and the second agent are administered simultaneously or concurrently. 36. The method of any one of claims 29-34, wherein the antagonist and the second agent are administered sequentially. 37. The method of any one of claims 1-36, wherein the antagonist and/or the second agent is administered parentally. 38. The method of any one of claims 22-37, wherein the antagonist is administered to the cancer tissue or infection site directly. 39. The method of any one of claims 1-38, wherein the antagonist is administered at a dose of about 0.001 μg/kg to about 100 mg/kg. 40. The method of any one of claims 22-39, wherein the individual has an increased number of immune cells in the cancer tissue or at the infection site after administration of the antagonist. 41. The method of claim 40, wherein the immune cells are T cells. 42. The method of claim 40 or claim 41, wherein the T cells are activated T cells. 43. The method of any one of claim 40-42, wherein the number of immune cells in the cancer tissue or at the infection site is increased by at least about 5% after administration of the antagonist. 44. The method of any one of claims 22-43, wherein immune cells in the cancer tissue or at the infection site produce an increased level of a cytokine after administration of the antagonist. 45. The method of claim 44, wherein the cytokine is IFNγ and/or IL-2. 46. The method of claim 39 or claim 40, wherein the level of the cytokine is increased by at least about 5% after administration of the antagonist."
claim_text_184_270_747_563_446 = "The invention claimed is: 1. An antibody or an antigen-binding fragment, analog or derivative thereof, directed against a heparanase enzyme, wherein the antibody, antigen-binding fragment, analog or derivative thereof comprises six complementarity-determining regions (CDRs), of SEQ ID NO: 1 to SEQ ID NO: 6. 2. The antibody or antigen-binding fragment, analog or derivative of claim 1, wherein said antibody or antigen-binding fragment, analog or derivative is murine or human or is humanized. 3. The antibody or antigen-binding fragment, analog or derivative of claim 1, comprising the amino acid sequence of SEQ ID NO: 7 or SEQ ID NO: 8. 4. The antibody or antigen-binding fragment, analog or derivative of claim 1, wherein the antibody fragment is selected from the group consisting of: Fab, Fab′, F(ab′)2, Fd, Fd′, Fv, dAb, isolated CDR region, single chain antibody, diabodies, and linear antibodies. 5. A pharmaceutical composition comprising the antibody or antigen-binding fragment, analog or derivative of claim 1 and a pharmaceutical acceptable carrier. 6. An isolated polynucleotide sequence encoding the antibody of claim 1. 7. The isolated polynucleotide sequence of claim 6, comprising the nucleotide sequence as set forth in SEQ ID NO: 9 to SEQ ID NO: 16. 8. A vector comprising the polynucleotide sequence of claim 6. 9. A cell comprising the antibody or antigen-binding fragment, analog or derivative of claim 1. 10. A cell comprising the isolated polynucleotide sequence of claim 6. 11. A cell comprising the vector of claim 8. 12. A pharmaceutical composition comprising the isolated polynucleotide sequence of claim 6 and a pharmaceutically acceptable carrier. 13. A pharmaceutical composition comprising the vector of claim 8 and a pharmaceutically acceptable carrier."
claim_text_196_857_624_941_935 = "1. An anti-LAG3 monoclonal antibody, wherein the anti-LAG3 monoclonal antibody comprises a heavy chain variable region comprising HCDR1, HCDR2 and HCDR3 identical to CDR sequences of the heavy chain variable region as shown in SEQ ID NO: 2, 6 or 10, and a light chain variable region comprising LCDR1, LCDR2 and LCDR3 identical to CDR sequences of the light chain variable region as shown in SEQ ID NO: 4, 8 or 12. 2. The anti-LAG3 monoclonal antibody of claim 1, wherein the anti-LAG3 monoclonal antibody comprises: 1) heavy chain complementarity determining regions: HCDR1 having an amino acid sequence as shown in SEQ ID No: 18, HCDR2 having an amino acid sequence as shown in SEQ ID No: 19, and HCDR3 having an amino acid sequence as shown in SEQ ID No: 20 or 21; and 2) light chain complementarity determining regions: LCDR1 having an amino acid sequence as shown in SEQ ID No: 22 or 23, LCDR2 having an amino acid sequence as shown in SEQ ID No: 24, and LCDR3 having an amino acid sequence as shown in SEQ ID No: 25. 3. The anti-LAG3 monoclonal antibody of claim 2, wherein the anti-LAG3 monoclonal antibody comprises a heavy chain variable region having an amino acid sequence as shown in SEQ ID NO: 2, 6 or 10, or a sequence with at least 85% homology thereto; and a light chain variable region having an amino acid sequence as shown in SEQ ID NO: 4, 8 or 12, or a sequence with at least 85% homology thereto. 4. The anti-LAG3 monoclonal antibody of claim 2, wherein the anti-LAG3 monoclonal antibody comprises a heavy chain composed of a heavy chain variable region having an amino acid sequence as shown in SEQ ID NO: 2, 6 or 10, or a sequence with at least 85% homology thereto, and a heavy chain constant region as shown in SEQ ID NO: 14; and a light chain composed of a light chain variable region having an amino acid sequence as shown in SEQ ID NO: 4, 8 or 12, or a sequence with at least 85% homology thereto, and a light chain constant region as shown in SEQ ID NO: 16. 5. The anti-LAG3 monoclonal antibody of claim 1, wherein the anti-LAG3 monoclonal antibody is a full-length sequence of the antibody or an antigen-binding fragment comprising the anti-LAG3 antibody, wherein the antigen-binding fragment of the anti-LAG3 antibody is Fab, Fab′, F(ab′)2, Fv or scFv. 6. A nucleotide molecule, wherein the nucleotide molecule encodes the anti-LAG3 monoclonal antibody of claim 1. 7. The nucleotide molecule of claim 6, wherein in the nucleotide molecule, the nucleotide sequence encoding the heavy chain variable region of the anti-LAG3 monoclonal antibody is as shown in SEQ ID NO: 3, 7 or 11, and the nucleotide sequence encoding the light chain variable region of the anti-LAG3 monoclonal antibody is as shown in SEQ ID NO: 5, 9 or 13. 8. An expression vector, wherein the expression vector contains the nucleotide molecule of claim 6. 9. The expression vector of claim 8, wherein the expression vector is selected from one or more of pHLX101, pEE14.4, pCHO 1.0 or pcDNA3.1. 10. A host cell, wherein the host cell contains the expression vector of claim 8. 11. The host cell of claim 10, wherein the host cell is selected from one or more of COS, CHO, an HeLa cell line, a myeloid cell line such as an SP2/0 cell line, NS0, sf9, sf21, DH5α, BL21(DE3) or E. coli TG1, a YB2/0 cell line and a transformed B cell or a hybridoma cell. 12. A method for preparing the anti-LAG3 monoclonal antibody of claim 1, comprising the following steps: a) culturing a host cell containing an expression vector containing a nucleotide molecule encoding the anti-LAG3 monoclonal antibody of claim 1 to express the anti-LAG3 monoclonal antibody under an expression condition; and b) isolating and purifying the anti-LAG3 monoclonal antibody obtained in step a). 13. A composition, wherein the composition comprises the anti-LAG3 monoclonal antibody of claim 1 and a pharmaceutically acceptable carrier. 14. A method for resisting tumors, treating autoimmune diseases, and treating infectious diseases and/or resisting transplantation rejection reactions, comprising administering the anti-LAG3 monoclonal antibody of claim 1 or a composition comprising the anti-LAG3 monoclonal antibody of claim 1. 15. The method of claim 14, wherein the anti-LAG3 monoclonal antibody is administered alone or in combination with a drug for resisting tumors selected from an antibody drug and a small-molecule drug for resisting tumors. 16. A method of resisting tumors, treating autoimmune diseases, and treating infectious diseases and/or resisting transplantation rejection reactions, comprising administering the composition of claim 13. 17. The method of claim 14, the composition further comprises a drug for resisting tumors selected from an antibody drug and a small-molecule drug for resisting tumors. 18. The method of claim 15, wherein the antibody drug is an anti-PD-1 monoclonal antibody. 19. The method of claim 15, wherein the small-molecule drug is paclitaxel or 5-fluorouracil."
claim_text_013_287_333_155_311 = "A pharmaceutical composition comprising: i) a herpes gE protein, an active fragment of the protein, a variant of the protein, or a mixture of at least two of them, ii) an immunostimulatory composition comprising a saponin and a CpG oligodeoxynucleotide, or consisting of an adjuvant comprising a saponin and a CpG oligodeoxynucleotide, wherein the sequence of the CpG oligodeoxynucleotide has two or more copies of 5′-TTCGTT-3′ motif or 5′-TCGTCGTCG-3′ motif. 2. The pharmaceutical composition according to claim 1, wherein the sequence of the CpG oligodeoxynucleotide is selected from: CpG T1: TCG TTC OTT CGT TCG TTC OTT (SEQ ID NO: 2); CpG T2: TCG TTC OTT CGT TCG TTC GTT CGT T (SEQ ID NO: 3); and CpG T3: TCG TCG TCG TCG TCG TCG TCG (SEQ ID NO: 4); preferably, the sequence of the CpG oligodeoxynucleotide is CpG T1: TCG TTC OTT CGT TCG TTC GTT (SEQ ID NO: 2). 3. The pharmaceutical composition according to claim 1 or 2, wherein the saponin is one or more selected from the group consisting of quillaja saponin, ginsenoside, platycodin, astragaloside, notoginsenoside, glycyrrhizin, cortex albiziae saponin, ophiopogonin, saikosaponin and panax japonicus saponin. 4. The pharmaceutical composition according to claim 3, wherein the quillaja saponin is QS-7, QS-17, QS-18 or QS-21, preferably QS-21; the ginsenoside is ginsenoside Rg1, ginsenoside Rg3, ginsenoside Rb1 or ginsenoside Re; the platycodin is platycodin D, platycodin D2 or a mixture thereof; the astragaloside is astragalin A, astragaloside I, astragaloside H, or a mixture of two or more of these saponin monomers; the notoginseng saponin is notoginsenoside R1; the ophiopogonin is ophiopogonin D; the saikosaponin is saikosaponin a, saikosaponin d or a mixture thereof; the cortex albiziae saponin is cortex albiziae total saponins; the glycyrrhizin is total glycyrrhizins; and the panax japonicus saponin is panax japonicus total saponins. 5. The pharmaceutical composition according to any one of claims 1 to 4, wherein the adjuvant comprising a saponin is Iscom adjuvant. 6. The pharmaceutical composition according to any one of claims 1 to 5, wherein the CpG oligodeoxynucleotide comprises a phosphorothioate linkage. 7. The pharmaceutical composition according to any one of claims 1 to 6, wherein the CpG oligodeoxynucleotide is a thio-oligodeoxynucleotide. 8. The pharmaceutical composition according to any one of claims 1 to 7, wherein the CpG oligodeoxynucleotide is a perthio-oligodeoxynucleotide. 9. The pharmaceutical composition according to any one of claims 1 to 8, wherein the weight ratio of the CpG oligodeoxynucleotide to the saponin is 1˜40:0.1˜2, preferably 2˜40:0.1˜2. 10. The pharmaceutical composition according to any one of claims 1 to 9, wherein the weight ratio of the CpG oligodeoxynucleotide to the saponin is 2:1. 11. The pharmaceutical composition according to any one of claims 1 to 10, wherein the pharmaceutical composition further comprises: iii) a pharmaceutically acceptable carrier. 12. The pharmaceutical composition according to any one of claims 1 to 11, wherein the herpes gE protein comprises or consists of the amino acid sequence shown by SEQ ID NO: 1. 13. The pharmaceutical composition according to any one of claims 1 to 12, wherein the active fragment of the herpes gE protein comprises or consists of consecutive amino acids from position 1 to position X of SEQ ID NO: 1, wherein X is an integer between 507 and 518. 14. The pharmaceutical composition according to any one of claims 1 to 13, wherein the weight ratio between Components i) and ii) is 1:1.1˜42, preferably 1:2.1˜42. 15. The pharmaceutical composition according to any one of claims 1 to 14, wherein the weight ratio between Components i) and ii) is 1:3. 16. A herpes zoster or varicella vaccine comprising the pharmaceutical composition of any one of claims 1 to 15. 17. Use of the pharmaceutical composition according to any one of claims 1 to 15 in the preparation of a medicament for preventing and/or treating a varicella-zoster virus infection and/or a varicella-zoster virus mediated disease. 18. The use according to claim 17, wherein the varicella-zoster virus infection and/or the varicella-zoster virus mediated disease is selected from the group consisting of varicella, herpes zoster, and postherpetic neuralgia. 19. Use of the pharmaceutical composition according to any one of claims 1 to 15 in the preparation of a medicament for generating a humoral immune response and/or a cellular immune response against varicella-zoster virus in a subject. 20. The use according to claim 19, wherein the medicament is a herpes zoster vaccine or a varicella vaccine. 21. A method for preventing and/or treating a varicella-zoster virus infection and/or a varicella-zoster virus mediated disease comprising administering to a subject in need thereof an effective amount of the pharmaceutical composition according to any one of claims 1 to 15. 22. The method according to claim 21, wherein the varicella-zoster virus infection and/or the varicella-zoster virus mediated disease is selected from the group consisting of varicella, herpes zoster, and postherpetic neuralgia. 23. A method for generating a humoral immune response and/or a cellular immune response against varicella-zoster virus in a subject comprising administering to a subject in need thereof an effective amount of the pharmaceutical composition according to any one of claims 1 to 15."
claim_text_098_651_403_196_496 = "1. A method of producing an antibody-drug conjugate represented by Formula (I), Figure US20230074385A1-20230309-C00018 in the formula, Ab is an antibody or an antigen-binding fragment thereof, D is eribulin, m is an integer of 1 to 10, and p is an integer of 1 to 8, the method comprising: a step 1 of obtaining a compound represented by Formula (B) by reaction of eribulin or a salt thereof with a compound represented by Formula (A), Figure US20230074385A1-20230309-C00019 in the formula, m is an integer of 1 to 10 and X is a phenoxy group or a nitrophenoxy group, and Figure US20230074385A1-20230309-C00020 in the formula, m is an integer of 1 to 10; and a step 2 of obtaining the antibody-drug conjugate represented by Formula (I) by reaction of the compound represented by Formula (B) with Ab. 2. The method according to claim 1, wherein Ab comprises (i) a heavy chain domain comprising an amino acid sequence represented by SEQ ID NO: 1 and a light chain domain comprising an amino acid sequence represented by SEQ ID NO: 6, (ii) a heavy chain variable domain comprising an amino acid sequence represented by SEQ ID NO: 23 and a light chain variable domain comprising an amino acid sequence represented by SEQ ID NO: 24, (iii) a heavy chain variable domain comprising an amino acid sequence represented by SEQ ID NO: 27 and a light chain variable domain comprising an amino acid sequence represented by SEQ ID NO: 28, or (iv) a heavy chain domain comprising an amino acid sequence represented by SEQ ID NO: 347 and a light chain domain comprising an amino acid sequence represented by SEQ ID NO: 308. 3. The method according to claim 1 or 2, wherein p is 3 or 4. 4. The method according to any one of claims 1 to 3, wherein eribulin or the salt thereof is eribulin methanesulfonate. 5. The method according to any one of claims 1 to 4, wherein the step 1 is performed in the presence of a base. 6. A method of producing a compound represented by Formula (B), Figure US20230074385A1-20230309-C00021 in the formula, m is an integer of 1 to 10, the method comprising: a step of obtaining a compound represented by Formula (B) by reaction of eribulin or a salt thereof with a compound represented by Formula (A), Figure US20230074385A1-20230309-C00022 in the formula, m is an integer of 1 to 10 and X is a phenoxy group or a nitrophenoxy group. 7. The method according to claim 6, wherein the step is performed in the presence of a base. 8. A compound represented by Formula (A), Figure US20230074385A1-20230309-C00023 in the formula, m is an integer of 1 to 10 and X is a phenoxy group or a nitrophenoxy group."

In [202]:
#Filled in the df with missing claims
df.loc[df["lens_id"] == "032-240-698-890-336", "claims_text"] = claim_text_032_240_698_890_336
df.loc[df["lens_id"] == "053-807-865-739-075", "claims_text"] = claim_text_053_807_865_739_075
df.loc[df["lens_id"] == "029-853-159-129-12X", "claims_text"] = claim_text_029_853_159_129_12X
df.loc[df["lens_id"] == "022-873-617-525-132", "claims_text"] = claim_text_022_873_617_525_132
df.loc[df["lens_id"] == "058-165-013-366-539", "claims_text"] = claim_text_058_165_013_366_539
df.loc[df["lens_id"] == "184-270-747-563-446", "claims_text"] = claim_text_184_270_747_563_446
df.loc[df["lens_id"] == "196-857-624-941-935", "claims_text"] = claim_text_196_857_624_941_935
df.loc[df["lens_id"] == "013-287-333-155-311", "claims_text"] = claim_text_013_287_333_155_311
df.loc[df["lens_id"] == "098-651-403-196-496", "claims_text"] = claim_text_098_651_403_196_496

In [203]:
(df["claims_text"] == "").sum()

0

## Prepare files for API input
The next step is to prepare the text files to be inputted into API
- The three texts I can provide are Title, Abstract and Claims

<br>

<span style="background-color: yellow; color: black;">Note the limitations</span>
- If the claims references SEQ ID NO or Structures or Figures, I did not provide and include this information
- SEQ ID tables would significantly increase token length and are beyond the scope of this case study
- It would also require conversion of images into text, which would add preprocessing complexity

In [204]:
def extract_title(biblio):
    if not isinstance(biblio, dict):
        return ""
    
    titles = biblio.get("invention_title", [])
    
    if isinstance(titles, list) and len(titles) > 0:
        return titles[0].get("text", "")
    
    return ""

df["title"] = df["biblio"].apply(extract_title)

In [205]:
def extract_abstract(abstract_obj):
    if not isinstance(abstract_obj, list) or len(abstract_obj) == 0:
        return ""
    
    first_entry = abstract_obj[0]
    
    if isinstance(first_entry, dict):
        return first_entry.get("text", "")
    
    return ""

df["abstract_text"] = df["abstract"].apply(extract_abstract)

In [206]:
export_df = df[[
    "lens_id",
    "title",
    "abstract_text",
    "claims_text"
]].copy()

export_df = export_df.fillna("")

In [207]:
export_df.to_csv("../data/processed/patents_for_ai.csv", index=False)

## API Validation Using a Manually Curated Patent Set

First, the API will be tested on a manually curated patent list, specifically the ABL patents I have examined in "01_abl_bio_portfolio.ipynb"

This is done to test the prompts and edit the prompt (to fine tune and fix any errors)

_NOTE: this is a subset of the total ABL Bio's portfolio, it is 24 out of 37_
- For more info on which patents, look at "abl_patents_for_ai.csv"

##### **AI-based Section was ran in a data science course folder**
AI-based classification components were executed within a course-provided data science git hub repo
- Because they provided an OpenAI API gateway key, pre-configured environment dependencies and required Python packages

While execution occurred within the course environment, full scripts used for API-based claim classification are included below, along with the output screenshots

In [ ]:
import pandas as pd
document_folder = "../../05_src/assignment_chat/"

abl_df = pd.read_csv("abl_patents_for_ai.csv")

In [ ]:
#Provide the developer prompt
instructions =''' You are a pharmaceutical patent analyst specializing in antibody-drug conjugates (ADCs).
Classify patents based on claims content, not just title/abstract language. 
If a patent includes both composition claims and method-of-treatment claims, classify based on the broadest independent claim.
Follow strict JSON format. Keep reasoning_short concise (2-4 sentences).'''

In [ ]:
#User prompt
prompt='''Analyze the following patent:
TITLE:
{title}
ABSTRACT:
{abstract}
CLAIMS:
{claims}

Instructions:
Step 1. Determine the primary patent_type:
- "Composition" → Claims a drug, biologic, ADC construct, antibody, linker, payload, or therapeutic composition.
- "CMC" → Focuses on manufacturing, conjugation process, DAR control, purification, formulation, stability, analytical methods, or scale-up.
- "Clinical" → Focuses on treatment methods, dosing regimens, patient populations, combination therapies, or clinical use.
- "Other" → Does not primarily fall into the above categories.

Choose only ONE primary category based on the main inventive concept.

Step 2. If patent_type = "Composition", classify composition_subtype as ONE of:
- "Full ADC" → Specifies antibody + linker + payload.
- "Conjugated Linker" → Linker specified; antibody/payload broadly defined.
- "Conjugated Payload" → Payload specified; antibody/linker broadly defined.
- "Conjugated Antibody" → Antibody specified; linker/payload broadly defined.
- "Dual Combination" → Two of the three components (e.g., linker + payload) specified.
- "Unconjugated Linker" → Linker intermediate only.
- "Unconjugated Antibody" → Antibody intermediate only.
- "Unconjugated Payload" → Payload intermediate only.
- null → if not applicable.

Step 3. If patent_type = "CMC", classify cmc_subtype as ONE of:
- "DAR Control" → Controlling drug-to-antibody ratio or heterogeneity.
- "Conjugation Method" → Site-specific conjugation, enzymatic methods, engineered cysteines, glycan methods, click chemistry.
- "Process/Scale-Up" → Manufacturing optimization, yield improvement, reaction conditions.
- "Purification/Downstream" → Chromatography, aggregate removal, impurity removal.
- "Formulation/Stability" → Buffer systems, storage stability, lyophilization.
- "Analytical/Characterization" → DAR measurement, LC-MS methods, assay development.
- "Intermediate Production" → Linker/payload activated intermediates.
- null → if not applicable.

Step 4. If patent_type = "Clinical":
- Extract disease indications that are explicitly claimed as being treated, prevented, or managed.
- Do NOT extract diseases mentioned only in background or examples.
- Extract specific patient populations only if they are part of a claimed method (e.g., refractory patients, HER2+, metastatic, pediatric, etc.).

Return ONLY valid JSON in this format:
{{
  "patent_type": "",
  "composition_subtype": null,
  "cmc_subtype": null,
  "clinical_indications": [],
  "clinical_population": [],
  "reasoning_short": ""
}}

'''

In [ ]:
def classify_patent(row):
    filled_prompt = prompt.format(
        title=row['title'],
        abstract=row['abstract_text'],
        claims=row['claims_text']
    )
    
    response = client.chat.completions.create(
        model="gpt-4o-mini", #specify model
        messages=[
            {"role": "system", "content": instructions},
            {"role": "user", "content": filled_prompt}
        ],
        response_format={"type": "json_object"},
        temperature=0
    )
    
    return json.loads(response.choices[0].message.content)

In [ ]:
results = []
for idx, row in abl_df.iterrows():
    print(f"Processing {idx+1}/{len(abl_df)}: {row['lens_id']}")
    try:
        result = classify_patent(row)
        result['lens_id'] = row['lens_id']
        results.append(result)
    except Exception as e:
        print(f"  Error: {e}")
        results.append({'lens_id': row['lens_id'], 'error': str(e)})

results_df = pd.DataFrame(results)
results_df.to_csv("abl_patents_classified.csv", index=False)
print("Done!")
results_df.head()

I ran this with model 4o and with 4o-mini to compare the labeling results
- As expected, there is a decrease in quality for mini
- The broader bins (composition or clinical or CMC) remains the same; so macro-level classification is still strong in 4o-mini
- But subtype labeling is weaker
- 4o-mini model classifies plain antibodies and bispecific antibodies as "conjugated antibody" even when no linker or payload is present
- The reasoning is even "classifying it as a conjugated antibody since it specifies the antibody structure without detailing a linker or payload.” -> which is contradictory (conceptual drift)
- Though mini was able to extract more disease detail

<br>

**Overall, suggests:**
- Macro-level patent type classification remained stable,
- Clinical entity extraction improved 
- Structural classification degraded (subtype prediction)

**results_df.head() for 4o-model results:**
![title](../data/images/abl_bio_api_test_4o.png)
- The file can also be found in this repo, as `data/ai_results/abl_patents_classified_4o_model.csv`

<br>

**results_df.heaf for 4o-mini results**:
![title](../data/images/abl_bio_api_test_4omini.png)
- The file can also be found in this repo, as `data/ai_results/abl_patents_classified_4omini_model.csv`

### Comparison of Manual to API Classification

**Manual Categorization**  
From 01_abl_bio_portfolio.ipynb, I manually had assessed that this patent collection had:

1) Pure Antibody Composition Patents (n = 9)
    - Families: 2, 4, 5, 7, 9, 12, 13, 15, 19
    - These are classic composition-of-matter antibody filings focused on specific antigen-binding sequences.

2) Bi-Specific Antibody Composition Patents (n = 10)
    - Families: 1, 8, 11, 14, 17, 18, 20, 21, 22, 24
    - These patents claim dual-targeting antibody constructs

3) ADC Composition Patents (Antibody–Drug Conjugates) (n = 3)
    - Families: 3, 16, 23
    - These fell into three distinct structural subtypes:
        - Family 3 – Linker Platform Patent
        - Family 16 – Payload-Centric Patent
        - Family 23 – Full ADC Platform

4) Clinical Filing (n = 1)
    - Family: 10 | With the title, “A method of treating a solid tumor”

5) CMC / Manufacturing Patent (n = 1)
    - Family: 6 | With the title: “Method for Purifying Biologically Active Peptide by Using Protein A Affinity Chromatography”

<br>

**API Categorization**  
The APIs successfully categorized patents into the high-level buckets I gave: Composition, Clinical, CMC

## Trying to reduct ambiguity in subtype definition

Mini is overinterpreting “multi-component antibody” as conjugated.
- Need to edit prompt to define conjugation = covalent attachment to non-antibody payload
- Explicitly define bispecific antibodies as unconjugated
- Anchor everything to the broadest independent claim
- Add a decision hierarchy (ADC first, then antibody, then clinical, etc.)

In [ ]:
instructions = """
You are a pharmaceutical patent analyst specializing in antibody and antibody-drug conjugate (ADC) intellectual property.
Core principles:
- Base classification strictly on the BROADEST INDEPENDENT CLAIM.
- Prioritize structural claim scope over background, examples, or dependent claims.
- Distinguish clearly between:
  • Unconjugated antibodies (including bispecific/multispecific constructs)
  • Chemically conjugated antibodies (require covalent attachment to a non-antibody payload)
- Multiple binding domains do NOT constitute conjugation.
- Only classify as "Clinical" if the broadest independent claim is a method-of-treatment claim.
- Only classify as "CMC" if the primary inventive concept is manufacturing or process-focused.
Be conservative and structurally precise.
Return strict JSON only.
Keep reasoning_short concise (2–4 sentences).
"""

In [ ]:
prompt = '''Analyze the following patent:
TITLE:
{title}
ABSTRACT:
{abstract}
CLAIMS:
{claims}

Instructions:
IMPORTANT:
- Base all classification on the BROADEST INDEPENDENT CLAIM.
- Prioritize structural claim scope over background description.
- If multiple claim types exist, choose the dominant inventive concept.
------------------------------------------------------
Step 1. Determine the primary patent_type:
- "Composition" → Claims a chemical or biologic entity (antibody, ADC, linker, payload, or defined therapeutic construct).
- "CMC" → Focuses primarily on manufacturing processes, purification, conjugation methods, DAR control, formulation, analytical methods, or scale-up.
- "Clinical" → Claims a method of treatment, dosing regimen, patient population, or clinical use as the primary inventive concept.
- "Other" → Does not primarily fall into the above categories.
Choose ONLY ONE primary category.
If a patent contains both composition and method-of-treatment claims:
→ Select "Composition" IF the broadest independent claim is directed to the molecule/construct itself.
------------------------------------------------------
Step 2. If patent_type = "Composition", classify composition_subtype as ONE of:
DEFINITIONS:
- "Full ADC" → Explicitly claims antibody + linker + cytotoxic payload in a single defined construct.
- "Conjugated Linker" → Claims a specific linker for antibody conjugation; antibody/payload broadly defined.
- "Conjugated Payload" → Claims a specific cytotoxic payload for antibody conjugation; antibody/linker broadly defined.
- "Conjugated Antibody" → Antibody is covalently conjugated to a non-antibody payload (drug, toxin, radioisotope, etc.). Requires chemical conjugation.
- "Dual Combination" → Two of the three ADC components (e.g., linker + payload) are structurally defined together.
- "Unconjugated Antibody" → Antibody or bispecific/multispecific antibody ONLY. No covalent attachment to drug/toxin.
- "Unconjugated Linker" → Linker intermediate only.
- "Unconjugated Payload" → Cytotoxic drug intermediate only.
- null → if not applicable.
CRITICAL RULE:
- Bispecific or multispecific antibodies WITHOUT a covalently attached payload are classified as "Unconjugated Antibody".
- Multiple binding domains ≠ conjugation.
- Conjugation requires chemical attachment to a non-antibody payload.
------------------------------------------------------
Step 3. If patent_type = "CMC", classify cmc_subtype as ONE of:
- "DAR Control"
- "Conjugation Method"
- "Process/Scale-Up"
- "Purification/Downstream"
- "Formulation/Stability"
- "Analytical/Characterization"
- "Intermediate Production"
- null
------------------------------------------------------
Step 4. If patent_type = "Clinical":
- Extract ONLY diseases explicitly claimed in a treatment method.
- Do NOT extract diseases mentioned only in background.
- Extract patient populations ONLY if part of a claimed method (e.g., metastatic, HER2+, refractory).
------------------------------------------------------
Return ONLY valid JSON in this format:
{{
  "patent_type": "",
  "composition_subtype": null,
  "cmc_subtype": null,
  "clinical_indications": [],
  "clinical_population": [],
  "reasoning_short": ""
}}
'''

In [ ]:
def classify_patent(row):
    filled_prompt = prompt.format(
        title=row['title'],
        abstract=row['abstract_text'],
        claims=row['claims_text']
    )
    
    response = client.chat.completions.create(
        model="gpt-4o-mini", #specify model
        messages=[
            {"role": "system", "content": instructions},
            {"role": "user", "content": filled_prompt}
        ],
        response_format={"type": "json_object"},
        temperature=0
    )
    
    return json.loads(response.choices[0].message.content)

In [ ]:
results = []
for idx, row in abl_df.iterrows():
    print(f"Processing {idx+1}/{len(abl_df)}: {row['lens_id']}")
    try:
        result = classify_patent(row)
        result['lens_id'] = row['lens_id']
        results.append(result)
    except Exception as e:
        print(f"  Error: {e}")
        results.append({'lens_id': row['lens_id'], 'error': str(e)})

results_df = pd.DataFrame(results)
results_df.to_csv("abl_patents_classified.csv", index=False)
print("Done!")
results_df.head()

**The new results with v2 prompt:** 
![title](../data/images/abl_bio_api_test_4ominiv2.png)
- The file can also be found in this repo, as `data/ai_results/abl_patents_classified_4o_mini_model_v2.csv`


Subtyping is better but you'll notice clinical is now being overcalled 
- Lens ID 084-986-690-232-010 → classified as Clinical
- Lens ID 141-040-150-695-864 → classified as Clinical
- Lens ID 013-169-852-887-496 → classified as Clinical
-> seems to be over-prioritizing method-of-treatment claims even when composition is likely the broadest claim

In [ ]:
#Try again with emphasis in developer prompt
instructions = """
You are a pharmaceutical patent analyst specializing in antibody and ADC intellectual property.

STRICT DECISION PROCESS:

1. Identify Claim 1 (or the first independent claim).
2. If Claim 1 claims a molecule, antibody, ADC, linker, payload, or defined construct → classify as "Composition".
3. Only classify as "Clinical" if Claim 1 itself is a method-of-treatment claim.
4. Only classify as "CMC" if Claim 1 is primarily directed to a manufacturing or process method.
5. Do NOT override Composition simply because treatment claims appear later.

Structural rules:
- Bispecific/multispecific antibodies WITHOUT covalent drug attachment = "Unconjugated Antibody".
- Conjugation requires covalent attachment to a non-antibody payload.
- Be conservative and structurally precise.

Return strict JSON only.
Keep reasoning_short concise (2–4 sentences).
"""

**The results of v3 mini:** 
![title](../data/images/abl_bio_api_test_4ominiv3.png)
- The file can also be found in this repo, as `data/ai_results/abl_patents_classified_4o_mini_model_v3.csv`

Less conjugated antibodies being identified
- Before mini overcalled conjugation because it saw ADC language anywhere
- Now, mini undercalls conjugation unless Claim 1 is ADC

The addition of 'If Claim 1 is composition → classify as Composition' has stabilized Clinical vs Composition
- But it also means if conjugation language appears only in later independent claims, mini might miss it
- Model will label conjugated/ADC if: Claim 1 explicitly says so or covalent attachment is clearly in the broadest independent claim
- So it’s structurally conservative

For my objective (portfolio categorization), this is sufficient

However, for more detailed analysis (Like Freedom-to-operate, invalidity analysis, platform IP depth evaluation), this would not be

## Run API with v3 prompt in 4o-mini with entire 2,331 patent collection

In [ ]:
fullpatents = pd.read_csv("patents_for_ai.csv")
fullpatents.shape #confirmed it is 2331

In [ ]:
import time

results = []
for idx, row in fullpatents.iterrows():
    print(f"Processing {idx+1}/{len(fullpatents)}: {row['lens_id']}")
    try:
        result = classify_patent(row)
        result['lens_id'] = row['lens_id']
        results.append(result)
    except Exception as e:
        print(f"  Error on {row['lens_id']}: {e}")
        results.append({'lens_id': row['lens_id'], 'error': str(e)})
    
    time.sleep(0.5)  # small delay between calls

results_df = pd.DataFrame(results)
results_df.to_csv("patents_classified_v3mini.csv", index=False)
print("Done!")

The file can also be found in this repo, as `data/ai_results/patents_classified_v3mini.csv`

## Examine Patent Composition in ADC Oncology Space in US Jurisdiction

In [209]:
classified_df = pd.read_csv("../data/ai_results/patents_classified_v3mini.csv")

In [212]:
#Attach results to df of ~2000 patent families 
final_df = df.merge(classified_df, on='lens_id', how='left')
final_df.head()

,lens_id,jurisdiction,doc_number,kind,date_published,doc_key,docdb_id,lang,biblio,families,...,publication_type,claims_text,title,abstract_text,patent_type,composition_subtype,cmc_subtype,clinical_indications,clinical_population,reasoning_short
0,001-164-692-658-169,US,9107960,B2,2015-08-18,US_9107960_B2_20150818,443471947,en,{'publication_reference': {'jurisdiction': 'US...,{'simple_family': {'members': [{'document_id':...,...,GRANTED_PATENT,"1. A method to produce a compound, CL2A-SN-38,...",Antibody-SN-38 immunoconjugates with a CL2A li...,The present invention concerns improved method...,CMC,NaN,Conjugation Method,[],[],Claim 1 describes a method for producing a com...
1,039-300-232-515-637,US,9334318,B1,2016-05-10,US_9334318_B1_20160510,452042120,en,{'publication_reference': {'jurisdiction': 'US...,{'simple_family': {'members': [{'document_id':...,...,GRANTED_PATENT,1. A multivalent antibody comprising (a) a fir...,Multivalent DLL3 antibodies,"Novel modulators, including antibodies and der...",Composition,Unconjugated Antibody,NaN,[],[],"Claim 1 describes a multivalent antibody, whic..."
2,094-825-731-979-424,US,12318455,B2,2025-06-03,US_12318455_B2_20250603,631938788,en,{'publication_reference': {'jurisdiction': 'US...,{'simple_family': {'members': [{'document_id':...,...,GRANTED_PATENT,1. An antibody-drug conjugate or a pharmaceuti...,Anti-HER2 antibody-drug conjugate and applicat...,An anti-human epidermal growth factor receptor...,Composition,Full ADC,NaN,[],[],Claim 1 explicitly claims an antibody-drug con...
3,165-451-121-516-190,US,20160129013,A1,2016-05-12,US_20160129013_A1_20160512,452234872,en,{'publication_reference': {'jurisdiction': 'US...,{'simple_family': {'members': [{'document_id':...,...,PATENT_APPLICATION,1 . A method of treating a mammal having a pro...,TARGETED PYRROLOBENZODIAZAPINE CONJUGATES,Provided are Conjugate comprising PBDs conjuga...,Clinical,NaN,NaN,['proliferative disease'],['mammal'],Claim 1 is a method of treating a mammal havin...
4,064-424-066-709-583,US,11944689,B2,2024-04-02,US_11944689_B2_20240402,609044858,en,{'publication_reference': {'jurisdiction': 'US...,{'simple_family': {'members': [{'document_id':...,...,GRANTED_PATENT,"1. A Ligand Drug Conjugate (LDC) compound, whe...",Drug conjugates with self-stabilizing linkers ...,Compounds and compositions are disclosed in wh...,Composition,Full ADC,NaN,"['cancer', 'autoimmune disease']",[],Claim 1 describes a Ligand Drug Conjugate comp...

In [213]:
final_df['patent_type'].value_counts(dropna=False)

patent_type
Clinical       1235
Composition    1064
CMC              28
Other             4
Name: count, dtype: int64

In [214]:
type_summary = (
    final_df['patent_type']
    .value_counts()
    .reset_index()
)
type_summary.columns = ['patent_type', 'count']
type_summary['percent'] = (
    type_summary['count'] / type_summary['count'].sum() * 100
)
type_summary

   patent_type  count    percent
0     Clinical   1235  52.981553
1  Composition   1064  45.645646
2          CMC     28   1.201201
3        Other      4   0.171600

In [215]:
#Examining subtype may be less accurate (saw undercalling of conjugation) but for insight and estimation:
comp_df = final_df[final_df['patent_type'] == 'Composition']

print(comp_df['composition_subtype'].value_counts())
print("\n", comp_df['composition_subtype'].value_counts(normalize=True) * 100)

composition_subtype
Unconjugated Antibody    374
Full ADC                 230
Conjugated Antibody      134
Dual Combination          32
Conjugated Payload        28
Conjugated Linker         21
Other                      1
Name: count, dtype: int64

 composition_subtype
Unconjugated Antibody    45.609756
Full ADC                 28.048780
Conjugated Antibody      16.341463
Dual Combination          3.902439
Conjugated Payload        3.414634
Conjugated Linker         2.560976
Other                     0.121951
Name: proportion, dtype: float64

In [216]:
final_df.columns

Index(['lens_id', 'jurisdiction', 'doc_number', 'kind', 'date_published',
       'doc_key', 'docdb_id', 'lang', 'biblio', 'families', 'sequence_listing',
       'legal_status', 'abstract', 'claims', 'description', 'publication_type',
       'claims_text', 'title', 'abstract_text', 'patent_type',
       'composition_subtype', 'cmc_subtype', 'clinical_indications',
       'clinical_population', 'reasoning_short'],
      dtype='object')

In [217]:
final_df.loc[0, 'biblio']

{'publication_reference': {'jurisdiction': 'US',
  'doc_number': '9107960',
  'kind': 'B2',
  'date': '2015-08-18'},
 'application_reference': {'jurisdiction': 'US',
  'doc_number': '201414255508',
  'kind': 'A',
  'date': '2014-04-17'},
 'application_number': '14/255,508',
 'priority_claims': {'claims': [{'jurisdiction': 'US',
    'doc_number': '201414255508',
    'kind': 'A',
    'date': '2014-04-17',
    'sequence': 1},
   {'jurisdiction': 'US',
    'doc_number': '201313948732',
    'kind': 'A',
    'date': '2013-07-23',
    'sequence': 2},
   {'jurisdiction': 'US',
    'doc_number': '201261736684',
    'kind': 'P',
    'date': '2012-12-13',
    'sequence': 3},
   {'jurisdiction': 'US',
    'doc_number': '201361749548',
    'kind': 'P',
    'date': '2013-01-07',
    'sequence': 4}],
  'earliest_claim': {'date': '2012-12-13'}},
 'invention_title': [{'text': 'Antibody-SN-38 immunoconjugates with a CL2A linker',
   'lang': 'en'}],
 'parties': {'examiners': {'primary_examiner': {'department': '1642',
    'extracted_name': {'value': 'Yan Xiao'}}},
  'applicants': [{'residence': 'US',
    'extracted_name': {'value': 'IMMUNOMEDICS INC'}},
   {'residence': 'US', 'extracted_name': {'value': 'IMMUNIMEDICS INC'}}],
  'inventors': [{'residence': 'US',
    'sequence': 1,
    'extracted_name': {'value': 'GOVINDAN SERENGULAM V'}},
   {'residence': 'US',
    'sequence': 2,
    'extracted_name': {'value': 'GALE JONATHAN B'}},
   {'residence': 'US',
    'sequence': 3,
    'extracted_name': {'value': 'HOLMAN NICHOLAS J'}},
   {'residence': 'US',
    'sequence': 4,
    'extracted_name': {'value': 'GOLDENBERG DAVID M'}}],
  'agents': [{'extracted_name': {'value': 'Richard A. Nakashima'}}],
  'owners_all': [{'recorded_date': '2014-08-21',
    'execution_date': '2014-08-07',
    'extracted_name': {'value': 'JOHNSON MATTHEY PHARMACEUTICAL MATERIALS INC'},
    'extracted_address': '25 PATTON ROAD, DEVENS, MASSACHUSETTS, 01434'},
   {'recorded_date': '2014-08-21',
    'execution_date': '2014-08-13',
    'extracted_name': {'value': 'IMMUNOMEDICS INC'},
    'extracted_address': '300 AMERICAN ROAD, MORRIS PLAINS, NEW JERSEY, 07950'}]},
 'classifications_ipcr': {'classifications': [{'symbol': 'A61K47/48',
    'classification_value': 'I',
    'classification_symbol_position': 'F'},
   {'symbol': 'A61K31/337',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/4184',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/4375',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/454',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/4745',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/513',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/675',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/7088',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/713',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K33/24',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K38/17',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K39/00',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K39/395',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K45/06',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K48/00',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61N5/10',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/28',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/30',
    'classification_value': 'I',
    'classification_symbol_position': 'L'}]},
 'classifications_cpc': {'classifications': [{'symbol': 'A61K31/337',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/4184',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/4375',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/454',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/513',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/675',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/7088',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/713',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/2803',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/2833',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/2887',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/30',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/3007',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K2317/92',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K2317/94',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61N2005/1098',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K39/39558',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K2039/505',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K2039/507',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K2317/77',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K38/395',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6889',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6849',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6853',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6855',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6857',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6859',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6863',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6869',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K45/06',
    'classification_value': 'I',
    'classification_symbol_position': 'F'},
   {'symbol': 'A61K31/4745',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'B01D15/08',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6867',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6851',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61P31/00',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61P35/00',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61P35/02',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61P35/04',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61P37/06',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'Y02P20/55',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/68037',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/60',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6853',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6849',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6855',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6863',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61P35/00',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/4745',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6803',
    'classification_value': 'I',
    'classification_symbol_position': 'F'},
   {'symbol': 'A61K45/06',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07D491/22',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K45/06',
    'classification_value': 'I',
    'classification_symbol_position': 'F'},
   {'symbol': 'A61K31/4745',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/337',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/4184',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/4375',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/454',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/513',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/675',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/7088',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K31/713',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/2803',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/2833',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/2887',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/30',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/3007',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K2317/92',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K2317/94',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61N2005/1098',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K39/39558',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K2039/505',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K2039/507',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K2317/77',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K38/395',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6857',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6863',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6855',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6869',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6849',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6859',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6853',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6889',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6801',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/68037',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/2851',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/3092',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/3015',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/3023',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/303',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/3046',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'B01D15/08',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K16/3061',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'C07K2317/24',
    'classification_value': 'A',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6867',
    'classification_value': 'I',
    'classification_symbol_position': 'L'},
   {'symbol': 'A61K47/6851',
    'classification_value': 'I',
    'classification_symbol_position': 'L'}]},
 'references_cited': {'citations': [{'sequence': 1,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '2010104589',
      'kind': 'A1',
      'date': '2010-04-29'},
     'lens_id': '089-237-464-894-482'},
    'cited_phase': 'SEA'},
   {'sequence': 2,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '2014058067',
      'kind': 'A1',
      'date': '2014-02-27'},
     'lens_id': '003-084-047-809-297'},
    'cited_phase': 'SEA'},
   {'sequence': 3,
    'nplcit': {'text': 'Lebreton et al. (Biotechnol. Bioeng., 2008, 100: 964-974).',
     'lens_id': '099-549-832-046-088',
     'external_ids': ['10.1002/bit.21842', '18393314']},
    'cited_phase': 'SEA'},
   {'sequence': 1,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '4036945',
      'kind': 'A',
      'date': '1977-07-19'},
     'lens_id': '045-579-541-908-838'},
    'cited_phase': 'APP'},
   {'sequence': 2,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '4046722',
      'kind': 'A',
      'date': '1977-09-06'},
     'lens_id': '045-381-336-489-677'},
    'cited_phase': 'APP'},
   {'sequence': 3,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '4200690',
      'kind': 'A',
      'date': '1980-04-29'},
     'lens_id': '140-090-500-896-113'},
    'cited_phase': 'APP'},
   {'sequence': 4,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '4331647',
      'kind': 'A',
      'date': '1982-05-25'},
     'lens_id': '065-136-760-401-79X'},
    'cited_phase': 'APP'},
   {'sequence': 5,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '4359457',
      'kind': 'A',
      'date': '1982-11-16'},
     'lens_id': '005-787-977-175-44X'},
    'cited_phase': 'APP'},
   {'sequence': 6,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '4699784',
      'kind': 'A',
      'date': '1987-10-13'},
     'lens_id': '174-148-754-833-975'},
    'cited_phase': 'APP'},
   {'sequence': 7,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '4704692',
      'kind': 'A',
      'date': '1987-11-03'},
     'lens_id': '074-447-246-598-301'},
    'cited_phase': 'APP'},
   {'sequence': 8,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '4816567',
      'kind': 'A',
      'date': '1989-03-28'},
     'lens_id': '114-009-432-454-132'},
    'cited_phase': 'APP'},
   {'sequence': 9,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '4824659',
      'kind': 'A',
      'date': '1989-04-25'},
     'lens_id': '191-567-336-032-457'},
    'cited_phase': 'APP'},
   {'sequence': 10,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '4916213',
      'kind': 'A',
      'date': '1990-04-10'},
     'lens_id': '115-058-782-795-380'},
    'cited_phase': 'APP'},
   {'sequence': 11,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '4918163',
      'kind': 'A',
      'date': '1990-04-17'},
     'lens_id': '181-811-938-362-380'},
    'cited_phase': 'APP'},
   {'sequence': 12,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '4925922',
      'kind': 'A',
      'date': '1990-05-15'},
     'lens_id': '046-142-053-257-217'},
    'cited_phase': 'APP'},
   {'sequence': 13,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '4932412',
      'kind': 'A',
      'date': '1990-06-12'},
     'lens_id': '184-705-475-226-867'},
    'cited_phase': 'APP'},
   {'sequence': 14,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '4946778',
      'kind': 'A',
      'date': '1990-08-07'},
     'lens_id': '130-421-270-059-352'},
    'cited_phase': 'APP'},
   {'sequence': 15,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '5057313',
      'kind': 'A',
      'date': '1991-10-15'},
     'lens_id': '030-298-333-183-830'},
    'cited_phase': 'APP'},
   {'sequence': 16,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '5106955',
      'kind': 'A',
      'date': '1992-04-21'},
     'lens_id': '115-287-025-490-060'},
    'cited_phase': 'APP'},
   {'sequence': 17,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '5112954',
      'kind': 'A',
      'date': '1992-05-12'},
     'lens_id': '104-799-504-947-208'},
    'cited_phase': 'APP'},
   {'sequence': 18,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '5122368',
      'kind': 'A',
      'date': '1992-06-16'},
     'lens_id': '116-209-435-093-060'},
    'cited_phase': 'APP'},
   {'sequence': 19,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '5134075',
      'kind': 'A',
      'date': '1992-07-28'},
     'lens_id': '016-531-601-482-310'},
    'cited_phase': 'APP'},
   {'sequence': 20,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '5171665',
      'kind': 'A',
      'date': '1992-12-15'},
     'lens_id': '117-665-062-103-38X'},
    'cited_phase': 'APP'},
   {'sequence': 21,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '5196337',
      'kind': 'A',
      'date': '1993-03-23'},
     'lens_id': '025-164-356-944-247'},
    'cited_phase': 'APP'},
   {'sequence': 22,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '5204095',
      'kind': 'A',
      'date': '1993-04-20'},
     'lens_id': '132-579-391-084-717'},
    'cited_phase': 'APP'},
   {'sequence': 23,
    'patcit': {'document_id': {'jurisdiction': 'US',
      'doc_number': '5229275',
      'kind': 'A',
      'date': '1993-07-20'},
     'lens_id': '069-222-504-072-073'},
    'cited_phase': 'APP'},

In [224]:
#There are some rows where owner column is filled and is different from applicant
import ast

# 1. extract applicants
def extract_applicants(record):
    try:
        if isinstance(record, str):
            record = ast.literal_eval(record)
        applicants = record.get("parties", {}).get("applicants", [])
        names = [a.get("extracted_name", {}).get("value") for a in applicants]
        return [n for n in names if n]
    except:
        return []
    
final_df["applicant_list"] = final_df["biblio"].apply(extract_applicants)

In [225]:
# 2. extract owners
def extract_owners(record):
    try:
        if isinstance(record, str):
            record = ast.literal_eval(record)
        owners = record.get("parties", {}).get("owners_all", [])
        names = [o.get("extracted_name", {}).get("value") for o in owners]
        return [n for n in names if n]
    except:
        return []

final_df["owner_list"] = final_df["biblio"].apply(extract_owners)
print(f"No owners: {final_df['owner_list'].apply(lambda x: len(x) == 0).sum()} / {len(final_df)}")

# 3. create assignee
final_df["assignee_list"] = final_df.apply(
    lambda row: row["owner_list"] if len(row["owner_list"]) > 0 else row["applicant_list"],
    axis=1
)

No owners: 455 / 2331

In [227]:
#Grab owner information from biblio data
def extract_applicants(record):
    try:
        # If stored as string, convert to dict
        if isinstance(record, str):
            record = ast.literal_eval(record)

        applicants = record.get("parties", {}).get("applicants", [])
        names = [a.get("extracted_name", {}).get("value") for a in applicants]
        return names
    except:
        return []

final_df["assignee_list"] = final_df["biblio"].apply(extract_applicants)

In [228]:
#Explode to one Row per Applicant
exploded_df = final_df.explode("assignee_list")

In [229]:
top_companies = (
    exploded_df["assignee_list"]
    .value_counts()
)

top_companies.head(30)

assignee_list
GENENTECH INC                                    79
DAIICHI SANKYO CO LTD                            51
HOFFMANN LA ROCHE                                37
UNIV TEXAS                                       35
NOVARTIS AG                                      34
JANSSEN BIOTECH INC                              31
BRISTOL MYERS SQUIBB CO                          30
UNIV CALIFORNIA                                  29
IMMUNOGEN INC                                    27
MEDIMMUNE LTD                                    26
SEAGEN INC                                       24
DANA FARBER CANCER INST INC                      21
MAYO FOUND MEDICAL EDUCATION & RES               20
EISAI R&D MAN CO LTD                             20
UNIV PENNSYLVANIA                                19
L E A F HOLDINGS GROUP LLC                       18
MEMORIAL SLOAN KETTERING CANCER CENTER           17
MERCK SHARP & DOHME LLC                          17
MASSACHUSETTS GEN HOSPITAL                       17
CHIA TAI TIANQING PHARMACEUTICAL GROUP CO LTD    17
PFIZER                                           16
INCYTE CORP                                      16
REGENERON PHARMA                                 16
AMGEN INC                                        15
INST NAT SANTE RECH MED                          15
UNIV LELAND STANFORD JUNIOR                      14
CHUGAI PHARMACEUTICAL CO LTD                     14
JUNO THERAPEUTICS INC                            14
CELGENE CORP                                     14
GENMAB AS                                        14
Name: count, dtype: int64

In [230]:
#What % of ADC families are controlled by top 15 filers?
top_companies.head(15).sum() / len(final_df["lens_id"].unique())

0.2072072072072072

### Look at Patent Composition of Top 15 (volume-based) companies in Global ADC Oncology Space

In [231]:
top50_names = top_companies.head(50).index.tolist()

top50_df = exploded_df[
    exploded_df["assignee_list"].isin(top50_names)
]

In [232]:
portfolio_breakdown = (
    top50_df
    .groupby(["assignee_list", "patent_type"])
    .size()
    .unstack(fill_value=0)
)

portfolio_breakdown = portfolio_breakdown.reindex(top50_names)
portfolio_breakdown

patent_type,CMC,Clinical,Composition,Other
assignee_list,,,,
GENENTECH INC,0,58,21,0
DAIICHI SANKYO CO LTD,4,9,38,0
HOFFMANN LA ROCHE,0,28,9,0
UNIV TEXAS,0,27,8,0
NOVARTIS AG,1,13,19,1
JANSSEN BIOTECH INC,0,27,4,0
BRISTOL MYERS SQUIBB CO,0,21,9,0
UNIV CALIFORNIA,0,20,9,0
IMMUNOGEN INC,4,7,16,0
MEDIMMUNE LTD,0,12,14,0
SEAGEN INC,0,19,5,0
DANA FARBER CANCER INST INC,0,17,4,0
MAYO FOUND MEDICAL EDUCATION & RES,0,11,9,0
EISAI R&D MAN CO LTD,1,13,6,0
UNIV PENNSYLVANIA,0,7,12,0
L E A F HOLDINGS GROUP LLC,0,0,18,0
MEMORIAL SLOAN KETTERING CANCER CENTER,0,8,9,0
MERCK SHARP & DOHME LLC,0,16,1,0
MASSACHUSETTS GEN HOSPITAL,0,14,3,0
CHIA TAI TIANQING PHARMACEUTICAL GROUP CO LTD,0,5,12,0
PFIZER,0,10,6,0
INCYTE CORP,0,13,3,0
REGENERON PHARMA,1,6,9,0
AMGEN INC,0,10,5,0
INST NAT SANTE RECH MED,0,11,4,0
UNIV LELAND STANFORD JUNIOR,0,9,5,0
CHUGAI PHARMACEUTICAL CO LTD,0,9,5,0
JUNO THERAPEUTICS INC,0,11,2,1
CELGENE CORP,0,12,2,0
GENMAB AS,0,12,2,0
UNIV YALE,0,6,8,0
ADC THERAPEUTICS SA,0,7,5,0
TORAY INDUSTRIES,0,1,11,0
IMMUNOMEDICS INC,1,10,1,0
US HEALTH,0,4,7,0
SANOFI SA,0,4,7,0
SEATTLE GENETICS INC,0,6,5,0
UNIV JOHNS HOPKINS,0,8,3,0
MERCK SHARP & DOHME,1,9,1,0
ABBVIE INC,0,4,7,0
ASTRAZENECA AB,0,9,1,0
SHANGHAI HENGRUI PHARMACEUTICAL CO LTD,1,0,9,0
MERCK PATENT GMBH,0,7,3,0
TAKEDA PHARMACEUTICALS CO,0,5,4,0
HARVARD COLLEGE,0,5,3,0
JIANGSU HENGRUI MEDICINE CO,0,2,6,0
SAMSUNG ELECTRONICS CO LTD,0,8,0,0
UNIV TOKYO,0,2,6,0
SICHUAN KELUN BIOTECH BIOPHARMACEUTICAL CO LTD,1,2,5,0
H LEE MOFFITT CANCER CT & RES,0,8,0,0

In [233]:
#For percentage
portfolio_pct = portfolio_breakdown.div(
    portfolio_breakdown.sum(axis=1),
    axis=0
) * 100

portfolio_pct = portfolio_pct.reindex(top50_names)

portfolio_pct.round(1)

patent_type,CMC,Clinical,Composition,Other
assignee_list,,,,
GENENTECH INC,0.0,73.4,26.6,0.0
DAIICHI SANKYO CO LTD,7.8,17.6,74.5,0.0
HOFFMANN LA ROCHE,0.0,75.7,24.3,0.0
UNIV TEXAS,0.0,77.1,22.9,0.0
NOVARTIS AG,2.9,38.2,55.9,2.9
JANSSEN BIOTECH INC,0.0,87.1,12.9,0.0
BRISTOL MYERS SQUIBB CO,0.0,70.0,30.0,0.0
UNIV CALIFORNIA,0.0,69.0,31.0,0.0
IMMUNOGEN INC,14.8,25.9,59.3,0.0
MEDIMMUNE LTD,0.0,46.2,53.8,0.0
SEAGEN INC,0.0,79.2,20.8,0.0
DANA FARBER CANCER INST INC,0.0,81.0,19.0,0.0
MAYO FOUND MEDICAL EDUCATION & RES,0.0,55.0,45.0,0.0
EISAI R&D MAN CO LTD,5.0,65.0,30.0,0.0
UNIV PENNSYLVANIA,0.0,36.8,63.2,0.0
L E A F HOLDINGS GROUP LLC,0.0,0.0,100.0,0.0
MEMORIAL SLOAN KETTERING CANCER CENTER,0.0,47.1,52.9,0.0
MERCK SHARP & DOHME LLC,0.0,94.1,5.9,0.0
MASSACHUSETTS GEN HOSPITAL,0.0,82.4,17.6,0.0
CHIA TAI TIANQING PHARMACEUTICAL GROUP CO LTD,0.0,29.4,70.6,0.0
PFIZER,0.0,62.5,37.5,0.0
INCYTE CORP,0.0,81.2,18.8,0.0
REGENERON PHARMA,6.2,37.5,56.2,0.0
AMGEN INC,0.0,66.7,33.3,0.0
INST NAT SANTE RECH MED,0.0,73.3,26.7,0.0
UNIV LELAND STANFORD JUNIOR,0.0,64.3,35.7,0.0
CHUGAI PHARMACEUTICAL CO LTD,0.0,64.3,35.7,0.0
JUNO THERAPEUTICS INC,0.0,78.6,14.3,7.1
CELGENE CORP,0.0,85.7,14.3,0.0
GENMAB AS,0.0,85.7,14.3,0.0
UNIV YALE,0.0,42.9,57.1,0.0
ADC THERAPEUTICS SA,0.0,58.3,41.7,0.0
TORAY INDUSTRIES,0.0,8.3,91.7,0.0
IMMUNOMEDICS INC,8.3,83.3,8.3,0.0
US HEALTH,0.0,36.4,63.6,0.0
SANOFI SA,0.0,36.4,63.6,0.0
SEATTLE GENETICS INC,0.0,54.5,45.5,0.0
UNIV JOHNS HOPKINS,0.0,72.7,27.3,0.0
MERCK SHARP & DOHME,9.1,81.8,9.1,0.0
ABBVIE INC,0.0,36.4,63.6,0.0
ASTRAZENECA AB,0.0,90.0,10.0,0.0
SHANGHAI HENGRUI PHARMACEUTICAL CO LTD,10.0,0.0,90.0,0.0
MERCK PATENT GMBH,0.0,70.0,30.0,0.0
TAKEDA PHARMACEUTICALS CO,0.0,55.6,44.4,0.0
HARVARD COLLEGE,0.0,62.5,37.5,0.0
JIANGSU HENGRUI MEDICINE CO,0.0,25.0,75.0,0.0
SAMSUNG ELECTRONICS CO LTD,0.0,100.0,0.0,0.0
UNIV TOKYO,0.0,25.0,75.0,0.0
SICHUAN KELUN BIOTECH BIOPHARMACEUTICAL CO LTD,12.5,25.0,62.5,0.0
H LEE MOFFITT CANCER CT & RES,0.0,100.0,0.0,0.0

In [234]:
#Overall the oncologu landscape has
final_df["patent_type"].value_counts(normalize=True) * 100

patent_type
Clinical       52.981553
Composition    45.645646
CMC             1.201201
Other           0.171600
Name: proportion, dtype: float64

The onology ADC landscape is:
- Clinical ~53%
- Composition ~46%
- CMC ~1%
- Other is negligible

The ADC patent landscape is predominantly clinically driven (~53%), indicating a development-stage competitive environment. However, composition filings remain substantial (~46%), reflecting continued platform-level and construct-level protection. Manufacturing IP (CMC) is relatively minimal (~1%), suggesting that competitive advantage is currently concentrated at the molecule and clinical positioning level rather than process control.


If overall space is composition-heavy but leaders are clinical-heavy…

That means:

Early-stage composition patents are fragmented among many small players.
Late-stage clinical protection is concentrated among top companies.

That’s powerful']

In [235]:
final_df["publication_type"].value_counts()

publication_type
PATENT_APPLICATION    1761
GRANTED_PATENT         570
Name: count, dtype: int64

~75% of ADC simple families in this dataset do not yet have a granted member

In [236]:
status_by_type = (
    final_df
    .groupby(["patent_type", "publication_type"])
    .size()
    .unstack(fill_value=0)
)

status_pct = status_by_type.div(
    status_by_type.sum(axis=1), axis=0
) * 100

status_pct.round(1)

publication_type  GRANTED_PATENT  PATENT_APPLICATION
patent_type
CMC                         32.1                67.9
Clinical                    24.5                75.5
Composition                 24.3                75.7
Other                        0.0               100.0

Grant Rate Is Uniform Across Types
So this is not:

“clinical is immature”

“composition is immature”

It’s simply:

The ADC field itself is recent and still prosecuting.


Because Composition and Clinical have almost identical grant rates (~24–25%):

This strongly suggests:

The wave of ADC filings happened in the same time window.

The field expanded aggressively in the past 5–7 years.

We are in a prosecution-heavy cycle, not a mature-lockdown cycle.


The ADC landscape is in an expansion phase characterized by aggressive filing across both molecule and clinical claims, rather than a stabilized platform-dominant environment
The core platform architecture is not monopolized

Many players are advancing assets in parallel

Our data shows: 
Composition and Clinical are expanding together

Both are heavily pending

No structural maturity gap between them

In [237]:
final_df.columns

Index(['lens_id', 'jurisdiction', 'doc_number', 'kind', 'date_published',
       'doc_key', 'docdb_id', 'lang', 'biblio', 'families', 'sequence_listing',
       'legal_status', 'abstract', 'claims', 'description', 'publication_type',
       'claims_text', 'title', 'abstract_text', 'patent_type',
       'composition_subtype', 'cmc_subtype', 'clinical_indications',
       'clinical_population', 'reasoning_short', 'owner_list',
       'applicant_list', 'assignee_list'],
      dtype='object')

In [238]:
final_df["date_published"] = pd.to_datetime(
    final_df["date_published"],
    errors="coerce"
)

In [239]:
final_df["year"] = final_df["date_published"].dt.year

In [240]:
counts = pd.crosstab(
    final_df["year"],
    final_df["publication_type"]
)

percentages = counts.div(counts.sum(axis=1), axis=0) * 100
percentages = percentages.round(1)

In [241]:
combined = counts.astype(str) + " (" + percentages.astype(str) + "%)"
combined

publication_type GRANTED_PATENT PATENT_APPLICATION
year
2006                   0 (0.0%)         1 (100.0%)
2008                   0 (0.0%)         2 (100.0%)
2009                  1 (33.3%)          2 (66.7%)
2010                   0 (0.0%)         6 (100.0%)
2011                  3 (30.0%)          7 (70.0%)
2012                  7 (35.0%)         13 (65.0%)
2013                  4 (33.3%)          8 (66.7%)
2014                 12 (37.5%)         20 (62.5%)
2015                 21 (41.2%)         30 (58.8%)
2016                 19 (34.5%)         36 (65.5%)
2017                 20 (32.3%)         42 (67.7%)
2018                 34 (42.5%)         46 (57.5%)
2019                 42 (33.1%)         85 (66.9%)
2020                 59 (43.1%)         78 (56.9%)
2021                 45 (23.4%)        147 (76.6%)
2022                 82 (27.3%)        218 (72.7%)
2023                 72 (18.5%)        318 (81.5%)
2024                 63 (15.9%)        334 (84.1%)
2025                 74 (18.2%)        333 (81.8%)
2026                 12 (25.5%)         35 (74.5%)

In [ ]:
#final_df.to_csv("../data/processed/df_AIclassified.csv", index=False)